"use client";
import Link from "next/link";
import {TaskPipeline,TaskHistory} from "./TaskPipeline";
import {PORTFOLIO_OPTIONS,getPortfolioId} from "@/lib/portal/portfolio-groups";
import {useEffect,useRef,useState} from "react";
import type {Task,TaskProject,TaskComment,TaskFile} from "@/lib/tasks/types";
import {statuses,dateLabel,todayAmsterdam,visibleProjects} from "@/lib/tasks/types";
import type {taskData} from "@/lib/tasks/store";
import {removeTask,updateTask,updateProject,readDetails,comment,reloadTasks,importProjects,updateProjectVisibility} from "@/app/taken/actions";
import "./tasks.css";
type Data=Awaited<ReturnType<typeof taskData>>;
export default function TasksClient({initial,userId,team,warning,initialTaskId,createNew,clientContext,initialProjectId}:{initial:Data;userId:string;team:boolean;warning:string;initialTaskId?:string;createNew?:boolean;clientContext?:{id:string;name:string};initialProjectId?:string}){
 const [data,setData]=useState(initial),[owner,setOwner]=useState(team?"":userId),[project,setProject]=useState(initialProjectId??""),[status,setStatus]=useState("open"),[query,setQuery]=useState("");
 const initialTask=initial.tasks.find(t=>t.id===initialTaskId);
 const [task,setTask]=useState<Task|null>(()=>initialTask??(createNew?{id:"",title:"",description:"",projectId:initialProjectId||"general",assigneeId:userId,status:"Te doen",deadline:"",version:0,checklist:[]}:null)),[draft,setDraft]=useState<TaskProject|null>(null),[details,setDetails]=useState<{comments:TaskComment[];files:TaskFile[]}>({comments:[],files:[]}),[note,setNote]=useState("");
 const [managing,setManaging]=useState(false),[projectSelection,setProjectSelection]=useState<string[]>([]),[projectSearch,setProjectSearch]=useState(""),[entityFilter,setEntityFilter]=useState("");
 const [error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);const selected=useRef(initialTask?.id??"");const fileInput=useRef<HTMLInputElement>(null);
 function newTask(){selected.current="";setDraft(null);setDetails({comments:[],files:[]});setNote("");setError("");setTask({id:"",title:"",description:"",projectId:project||"general",assigneeId:userId,status:"Te doen",deadline:"",version:0,checklist:[]});}
 async function openTask(t:Task){selected.current=t.id;setDraft(null);setTask({...t,checklist:t.checklist.map(i=>({...i}))});setError("");setMessage("");setNote("");setDetails({comments:[],files:[]});try{const loaded=await readDetails(t.id);if(selected.current===t.id)setDetails(loaded);}catch{if(selected.current===t.id)setError("Details konden niet worden geladen.");}}
 useEffect(()=>{if(!initialTaskId)return;let cancelled=false;readDetails(initialTaskId).then(value=>{if(!cancelled&&selected.current===initialTaskId)setDetails(value);}).catch(()=>{if(!cancelled)setError("Details konden niet worden geladen.");});return()=>{cancelled=true;};},[initialTaskId]);
 function patch<K extends keyof Task>(key:K,value:Task[K]){setTask(t=>t?{...t,[key]:value}:t);}
 async function save(){if(!task)return;setBusy(true);setError("");try{const result=await updateTask(task,!task.id?clientContext?.id:undefined);if(result.error)setError(result.error);else if(result.data){setData(result.data);setTask(null);selected.current="";setMessage("Taak opgeslagen.");}}catch{setError("Opslaan mislukt. Je invoer is behouden; probeer opnieuw.");}finally{setBusy(false);}}
 async function remove(){if(!task?.id||!window.confirm('Deze taak met checklist, opmerkingen, bijlagen en pipeline definitief verwijderen?'))return;setBusy(true);setError('');try{const result=await removeTask(task.id,task.version);if(result.error)setError(result.error);else if(result.data){setData(result.data);setTask(null);selected.current='';setMessage('Taak verwijderd.');}}catch{setError('Verwijderen mislukt. Probeer opnieuw.');}finally{setBusy(false);}}
 async function saveProject(){if(!draft)return;setBusy(true);setError("");try{const result=await updateProject(draft);if(result.error)setError(result.error);else if(result.data){setData(result.data);setDraft(null);setMessage("Project opgeslagen.");}}catch{setError("Project opslaan mislukt.");}finally{setBusy(false);}}
 async function addNote(){if(!task?.id)return;setBusy(true);setError("");try{const result=await comment(task.id,note);if(result.error)setError(result.error);else if(result.details){setDetails(result.details);setNote("");}}catch{setError("Opmerking toevoegen mislukt.");}finally{setBusy(false);}}
 async function upload(file:File|undefined){if(!file||!task?.id)return;if(file.size>3*1024*1024){setError("Een bijlage mag maximaal 3 MB zijn.");return;}setBusy(true);setError("");try{const form=new FormData();form.set("taskId",task.id);form.set("file",file);const response=await fetch("/api/task-files",{method:"POST",body:form});const result=await response.json();if(!response.ok)throw new Error(result.error||"Upload mislukt.");setDetails(await readDetails(task.id));}catch(e){setError(e instanceof Error?e.message:"Upload mislukt.");}finally{setBusy(false);if(fileInput.current)fileInput.current.value="";}}
 async function removeFile(id:string){if(!task?.id||!window.confirm("Deze bijlage verwijderen?"))return;setBusy(true);setError("");try{const response=await fetch("/api/task-files/"+id,{method:"DELETE"});if(!response.ok)throw new Error();setDetails(await readDetails(task.id));}catch{setError("Bijlage verwijderen mislukt.");}finally{setBusy(false);}}
 async function reload(sync=false){if((task||draft)&&!window.confirm("Niet opgeslagen invoer sluiten en de lijst vernieuwen?"))return;setBusy(true);setError("");try{if(sync){const result=await importProjects();if(result.error)setError(result.error);else if(result.data){setData(result.data);setMessage("Projecten uit Complete portefeuille bijgewerkt.");}}else setData(await reloadTasks());setTask(null);setDraft(null);selected.current="";}catch{setError("Vernieuwen mislukt.");}finally{setBusy(false);}}
 async function saveVisibility(){setBusy(true);setError("");try{const result=await updateProjectVisibility(projectSelection);if(result.error)setError(result.error);else if(result.data){setData(result.data);if(!visibleProjects(result.data.projects).some(p=>p.id===project))setProject("");setManaging(false);setMessage("Projectselectie opgeslagen voor alle collega's.");}}catch{setError("Opslaan mislukt. Probeer opnieuw.");}finally{setBusy(false);}}
 function manageProjects(){if((task||draft)&&!window.confirm("Niet opgeslagen invoer sluiten en projecten beheren?"))return;setTask(null);setDraft(null);selected.current="";setProjectSelection(data.projects.filter(p=>p.visible!==false&&!p.archived).map(p=>p.id));setProjectSearch("");setEntityFilter("");setManaging(true);setError("");setMessage("");}
 function close(){if(!window.confirm("Details sluiten? Niet opgeslagen wijzigingen gaan verloren."))return;setTask(null);setDraft(null);selected.current="";setError("");}
 const list=data.tasks.filter(t=>(!owner||t.assigneeId===owner)&&(!project||t.projectId===project)&&(status==="all"||status==="open"?status==="all"||t.status!=="Klaar":t.status===status)&&(!query||[t.title,t.description].some(s=>s.toLowerCase().includes(query.toLowerCase())))).sort((a,b)=>(a.deadline||"9999").localeCompare(b.deadline||"9999"));
 const managedProjects=data.projects.filter(p=>!p.archived&&(!entityFilter||(entityFilter==="manual"?p.source!=="portfolio":p.source==="portfolio"&&(getPortfolioId(p.entity??"")??"other")===entityFilter))&&[p.name,p.country,p.address].some(value=>value.toLowerCase().includes(projectSearch.toLowerCase())));
 const p=data.projects.find(p=>p.id===project);
 return <div><div className="task-bar"><h1>Taken</h1><div className="task-bar"><button disabled={busy} onClick={()=>void reload()}>Vernieuwen</button><button disabled={busy} onClick={newTask}>+ Taak toevoegen</button></div></div>{clientContext&&<p>Nieuwe taken worden gekoppeld aan <a href={"/klanten?klant="+clientContext.id}><strong>{clientContext.name}</strong> → klantdossier</a>.</p>}{warning&&<p role="status">{warning}</p>}
 <div className="task-filters"><label>Project<select value={project} onChange={e=>setProject(e.target.value)}><option value="">Alle projecten</option>{visibleProjects(data.projects).map(p=><option key={p.id} value={p.id}>{p.name}{p.country?" · "+p.country:""}{p.archived?" (archief)":""}</option>)}</select></label><label>Collega<select value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Alle collega&apos;s</option>{data.members.map(m=><option key={m.id} value={m.id}>{m.id===userId?"Mijn taken — ":""}{m.name}{!m.active?" (inactief)":""}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="open">Open taken</option><option value="all">Alle taken</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Zoeken<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Zoek een taak"/></label></div>
 <div className="task-bar"><div className="task-bar">{p&&<button disabled={busy} onClick={()=>{setTask(null);selected.current="";setDraft({...p});setError("");}}>Project bekijken</button>}<button disabled={busy} onClick={()=>{setTask(null);selected.current="";setDraft({id:"",name:"",country:"Nederland",address:"",status:"Lopend",description:"",source:"manual",archived:false});setError("");}}>+ Project toevoegen</button><button disabled={busy} onClick={manageProjects}>Projecten beheren</button><button disabled={busy} onClick={()=>void reload(true)}>Portefeuille bijwerken</button></div><span>{list.length} taken</span></div>
 <p role="alert" className="task-error">{error}</p><p role="status">{message}</p>
 {managing&&<section className="task-panel task-space"><div className="task-bar"><h2>Projecten beheren</h2><button disabled={busy} onClick={()=>setManaging(false)}>Annuleren</button></div><p>Vink de projecten aan die in het takenmenu mogen staan. Dit geldt voor alle collega’s. Bestaande taken blijven bewaard en zichtbaar bij Alle projecten. Marketing en Algemeen blijven beschikbaar.</p><label>BV<select value={entityFilter} onChange={e=>setEntityFilter(e.target.value)}><option value="">Alle BV’s en overige projecten</option>{PORTFOLIO_OPTIONS.map(bv=><option key={bv.id} value={bv.id}>{bv.label}</option>)}<option value="manual">Marketing, Algemeen en zelf toegevoegde projecten</option><option value="other">Overige portefeuilleprojecten</option></select></label><label>Project zoeken<input value={projectSearch} onChange={e=>setProjectSearch(e.target.value)} placeholder="Naam, land of adres"/></label><div className="task-bar"><button disabled={busy} onClick={()=>setProjectSelection([...new Set([...projectSelection,...managedProjects.map(p=>p.id)])])}>Getoonde projecten selecteren</button><button disabled={busy} onClick={()=>setProjectSelection(projectSelection.filter(id=>["general","marketing"].includes(id)||!managedProjects.some(p=>p.id===id)))}>Getoonde projecten verbergen</button><button disabled={busy} onClick={()=>setProjectSelection(["general","marketing"])}>Alleen Marketing en Algemeen</button></div><fieldset disabled={busy} style={{border:0,padding:0}}>{managedProjects.map(p=><label className="task-check" key={p.id}><input type="checkbox" checked={["general","marketing"].includes(p.id)||projectSelection.includes(p.id)} disabled={["general","marketing"].includes(p.id)} onChange={e=>setProjectSelection(e.target.checked?[...projectSelection,p.id]:projectSelection.filter(id=>id!==p.id))}/><span>{p.name}{p.country?" · "+p.country:""}{p.address?" · "+p.address:""}</span></label>)}</fieldset><button disabled={busy} onClick={()=>void saveVisibility()}>{busy?"Opslaan…":"Projectselectie opslaan"}</button></section>}
 <div className={"task-layout"+(task||draft?" open":"")}><section className="task-panel"><div className="task-row task-mini"><span>Taak</span><span>Project · collega</span><span>Deadline · status</span></div>{list.map(t=><div className="task-row" key={t.id}><button className="task-list-button" disabled={busy} onClick={()=>void openTask(t)}>{t.title}</button><span>{data.projects.find(p=>p.id===t.projectId)?.name}<br/><span className="task-mini">{data.members.find(m=>m.id===t.assigneeId)?.name??"Verwijderde collega"}</span></span><span>{t.status!=="Klaar"&&t.deadline&&t.deadline<todayAmsterdam()?"Te laat · ":""}{dateLabel(t.deadline)}<br/><span className="task-mini">{t.status} · {t.checklist.filter(c=>c.done).length}/{t.checklist.length} checklistpunten</span><br/><Link className="task-pipeline-link" href={"/taken/"+encodeURIComponent(t.id)+"/pipeline"}>Pipeline openen →</Link></span></div>)}{!list.length&&<p>Geen taken voor deze selectie.</p>}</section>
 {task&&<aside className="task-panel"><div className="task-bar"><h2>{task.id?"Taak bewerken":"Nieuwe taak"}</h2><button disabled={busy} onClick={close}>Sluiten</button></div><fieldset disabled={busy} style={{border:0,padding:0,minWidth:0}}><p className="task-mini">Datum taak gegeven: {task.createdAt?new Date(task.createdAt).toLocaleString('nl-NL',{timeZone:'Europe/Amsterdam'}):task.id?'Onbekend bij deze bestaande taak':'Wordt automatisch vastgelegd bij opslaan'}</p><label>Taaknaam<input value={task.title} maxLength={200} onChange={e=>patch("title",e.target.value)}/></label><label>Project<select value={task.projectId} onChange={e=>patch("projectId",e.target.value)}>{data.projects.filter(p=>(p.visible!==false&&!p.archived)||p.id===task.projectId).map(p=><option key={p.id} value={p.id}>{p.name}{p.country?" · "+p.country:""}</option>)}</select></label><label>Verantwoordelijke<select value={task.assigneeId} onChange={e=>patch("assigneeId",e.target.value)}>{data.members.filter(m=>m.active||m.id===task.assigneeId).map(m=><option key={m.id} value={m.id}>{m.name}{!m.active?" (inactief)":""}</option>)}</select></label><label>Omschrijving<textarea maxLength={12000} value={task.description} onChange={e=>patch("description",e.target.value)}/></label><label>Status<select value={task.status} onChange={e=>patch("status",e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Deadline<input type="date" value={task.deadline} onChange={e=>patch("deadline",e.target.value)}/></label><TaskPipeline task={task} onChange={(pipeline,currentStepId,status)=>setTask({...task,pipeline,currentStepId,status:status??task.status})}/><h3>Checklist</h3>{task.checklist.map((c,i)=><div className="task-check" key={c.id}><input aria-label={"Voltooid: "+c.text} type="checkbox" checked={c.done} onChange={e=>patch("checklist",task.checklist.map((v,j)=>j===i?{...v,done:e.target.checked}:v))}/><input aria-label="Checklistpunt" maxLength={500} value={c.text} onChange={e=>patch("checklist",task.checklist.map((v,j)=>j===i?{...v,text:e.target.value}:v))}/><button aria-label="Checklistpunt verwijderen" onClick={()=>patch("checklist",task.checklist.filter((_,j)=>i!==j))}>×</button></div>)}<button disabled={task.checklist.length>=100} onClick={()=>patch("checklist",[...task.checklist,{id:crypto.randomUUID(),text:"",done:false}])}>+ Checklistpunt</button><div className="task-space"><button onClick={()=>void save()}>{busy?"Opslaan…":"Taak opslaan"}</button></div>
 {task.id?<><TaskHistory id={task.id} revision={String(task.version)+':'+details.comments.length+':'+details.files.length}/><div className="task-space"><button className="portal-danger" onClick={()=>void remove()}>Taak verwijderen</button></div><h3>Bijlagen</h3><p className="task-mini">PNG, JPEG, WebP of PDF · maximaal 3 MB per bestand, 10 bijlagen per taak.</p>{details.files.map(f=><div className="task-file" key={f.id}><a href={"/api/task-files/"+f.id}>{f.name} ({Math.ceil(f.size/1024)} KB)</a><button onClick={()=>void removeFile(f.id)}>Verwijderen</button></div>)}<label>Bijlage toevoegen<input ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp,application/pdf" onChange={e=>void upload(e.target.files?.[0])}/></label><h3>Opmerkingen</h3>{details.comments.map(c=><div className="task-comment" key={c.id}><strong>{c.name}</strong> · <span className="task-mini">{new Date(c.createdAt).toLocaleString("nl-NL",{timeZone:"Europe/Amsterdam"})}</span><p>{c.text}</p></div>)}<label>Nieuwe opmerking<textarea value={note} maxLength={5000} onChange={e=>setNote(e.target.value)}/></label><button disabled={!note.trim()} onClick={()=>void addNote()}>Opmerking plaatsen</button></>:<p className="task-mini">Sla de taak eerst op om opmerkingen en bijlagen toe te voegen.</p>}</fieldset></aside>}
 {draft&&<aside className="task-panel"><div className="task-bar"><h2>{draft.id?"Projectgegevens":"Nieuw project"}</h2><button disabled={busy} onClick={close}>Sluiten</button></div>{draft.source==="portfolio"&&<p>Deze gegevens komen uit Complete portefeuille. Werk ze daar bij en haal de portefeuille opnieuw op.</p>}<fieldset disabled={busy||draft.source==="portfolio"||["marketing","general"].includes(draft.id)} style={{border:0,padding:0,minWidth:0}}>{([['name','Naam'],['country','Land'],['address','Adres'],['status','Status']] as const).map(([key,label])=><label key={key}>{label}<input value={draft[key]} maxLength={key==="address"?300:200} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<label>Omschrijving<textarea value={draft.description} maxLength={12000} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label><input type="checkbox" checked={draft.archived} onChange={e=>setDraft({...draft,archived:e.target.checked})}/> Project archiveren</label><button onClick={()=>void saveProject()}>Project opslaan</button></fieldset></aside>}
 </div></div>;
}
