export type FurnitureItem = {
  id: string;
  itemNo: string;
  name: string;
  category: string;
  location: string;
  purchasePrice: number;
  normalPrice: number;
  quantity: number;
  status: string;
  paymentStatus: string;
  supplier: string;
  productUrl: string;
  expectedDelivery: string;
  notes: string;
  images: string[];
  sourceRow?: number;
};

export const furnitureSeed: FurnitureItem[] = [
  { id: "excel-row-9", itemNo: "ART.01", name: "Minotti sofa color:", category: "Furniture", location: "Calderon de la Barca", purchasePrice: 14970, normalPrice: 24000, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 9 },
  { id: "excel-row-10", itemNo: "ART.02", name: "Lounge chair Vitra (with hocker)", category: "Furniture", location: "Calderon de la Barca", purchasePrice: 3800, normalPrice: 8600, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 10 },
  { id: "excel-row-11", itemNo: "ART.03", name: "Dining table Allinea Angelo 1.80", category: "Furniture", location: "Calle Margarita 7", purchasePrice: 10000, normalPrice: 23000, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 11 },
  { id: "excel-row-12", itemNo: "ART.04", name: "Salon table (Alnea Angelo Kyknos 1.60 x 1,15)", category: "Furniture", location: "Calle Margarita 7", purchasePrice: 3500, normalPrice: 8900, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 12 },
  { id: "excel-row-13", itemNo: "ART.05", name: "B&B Italia Husk with hocker (beige linnen and black leather cushions)", category: "Furniture", location: "Meuleveldlaan 30", purchasePrice: 1500, normalPrice: 3300, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 13 },
  { id: "excel-row-15", itemNo: "ART.06", name: "Jenssen bed 1", category: "Sleeping", location: "Calderon de la Barca", purchasePrice: 2200, normalPrice: 4500, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 15 },
  { id: "excel-row-16", itemNo: "ART.07", name: "Jenssen bed 2", category: "Sleeping", location: "Calderon de la Barca", purchasePrice: 1800, normalPrice: 3500, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 16 },
  { id: "excel-row-17", itemNo: "ART.08", name: "2 night tables and carpet", category: "Sleeping", location: "Calderon de la Barca", purchasePrice: 500, normalPrice: 500, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 17 },
  { id: "excel-row-19", itemNo: "ART.09", name: "Omschrijving ontbreekt", category: "Lighting", location: "Calderon de la Barca", purchasePrice: 1400, normalPrice: 2800, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "Productomschrijving ontbreekt in bronbestand.", images: [], sourceRow: 19 },
  { id: "excel-row-20", itemNo: "ART.10", name: "Foscarini alegro large", category: "Lighting", location: "Calderon de la Barca", purchasePrice: 2500, normalPrice: 6890, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 20 },
  { id: "excel-row-21", itemNo: "ART.11", name: "Henge round 3", category: "Lighting", location: "Calderon de la Barca", purchasePrice: 5000, normalPrice: 9000, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 21 },
  { id: "excel-row-22", itemNo: "ART.12", name: "Henge starlight black", category: "Lighting", location: "Calderon de la Barca", purchasePrice: 5000, normalPrice: 9000, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 22 },
  { id: "excel-row-23", itemNo: "ART.13", name: "Flos Arco - Black Marble - Limited Edition 40th Anniversary", category: "Lighting", location: "Meuleveldlaan 30", purchasePrice: 2000, normalPrice: 6000, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 23 },
  { id: "excel-row-25", itemNo: "ART.14", name: "Polyformdrop mirror (1.50 x 2.35) saddle hide", category: "Accessories", location: "Calderon de la Barca", purchasePrice: 2400, normalPrice: 5600, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 25 },
  { id: "excel-row-26", itemNo: "ART.15", name: "2 paintings Cobra Art", category: "Accessories", location: "Calderon de la Barca", purchasePrice: 3000, normalPrice: 5000, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 26 },
  { id: "excel-row-27", itemNo: "ART.16", name: "Wonderful World 2.50 x 1.20", category: "Accessories", location: "Meuleveldlaan 30", purchasePrice: 6500, normalPrice: 18000, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 27 },
  { id: "excel-row-28", itemNo: "ART.17", name: "Samsung TQ83S93DAEXXC OLED 83\"", category: "Accessories", location: "", purchasePrice: 3299, normalPrice: 3299, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 28 },
  { id: "excel-row-29", itemNo: "ART.18", name: "Soundbar", category: "Accessories", location: "", purchasePrice: 699, normalPrice: 699, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 29 },
  { id: "excel-row-30", itemNo: "ART.19", name: "2 Devialet Phantom", category: "Accessories", location: "Calderon de la Barca", purchasePrice: 2000, normalPrice: 3800, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "Bronlocatie: Calderon de la Barca / Jose.", images: [], sourceRow: 30 },
  { id: "excel-row-31", itemNo: "ART.20", name: "2 mirrors metal 90 x 2.30", category: "Accessories", location: "Meuleveldlaan 30", purchasePrice: 3400, normalPrice: 5600, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 31 },
  { id: "excel-row-32", itemNo: "ART.21", name: "Sumo Helmut Newton XXL", category: "Accessories", location: "Meuleveldlaan 30", purchasePrice: 6000, normalPrice: 7500, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 32 },
  { id: "excel-row-33", itemNo: "ART.22", name: "Annie Leibovitz Limited Edition Keith Haring", category: "Accessories", location: "Meuleveldlaan 30", purchasePrice: 3000, normalPrice: 4500, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 33 },
  { id: "excel-row-35", itemNo: "ART.23", name: "Pool table 2.63 x 1.42 M", category: "Funrooms", location: "Meuleveldlaan 30", purchasePrice: 4000, normalPrice: 4000, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 35 },
  { id: "excel-row-38", itemNo: "ART.24", name: "Kamado grill", category: "Outdoor", location: "Calderon de la Barca", purchasePrice: 2350, normalPrice: 2393, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 38 },
  { id: "excel-row-39", itemNo: "ART.25", name: "6 dining with table 2.80 and carpet", category: "Outdoor", location: "", purchasePrice: 1500, normalPrice: 0, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "Normale waarde ontbreekt in bronbestand.", images: [], sourceRow: 39 },
  { id: "excel-row-40", itemNo: "ART.26", name: "2 single daybeds 1 double", category: "Outdoor", location: "", purchasePrice: 1200, normalPrice: 0, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "Normale waarde ontbreekt in bronbestand.", images: [], sourceRow: 40 },
  { id: "excel-row-41", itemNo: "ART.27", name: "6 Kettal Maya outdoor chair with black cushion", category: "Outdoor", location: "Meuleveldlaan 30", purchasePrice: 5000, normalPrice: 7200, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 41 },
  { id: "excel-row-42", itemNo: "ART.28", name: "Kettal Plumon lounge (price incl. BTW)", category: "Outdoor", location: "Meuleveldlaan 30", purchasePrice: 23150, normalPrice: 46301, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 42 },
  { id: "excel-row-43", itemNo: "ART.29", name: "Kettal Plumon Dining set (price incl. BTW)", category: "Outdoor", location: "Meuleveldlaan 30", purchasePrice: 18715, normalPrice: 37430, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 43 },
  { id: "excel-row-44", itemNo: "ART.30", name: "Minotti patio lounge (price incl. BTW)", category: "Outdoor", location: "Meuleveldlaan 30", purchasePrice: 32021, normalPrice: 64042, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 44 },
  { id: "excel-row-45", itemNo: "ART.31", name: "Minotti Torii nest dining, 8 chairs, table 2.80 M", category: "Outdoor", location: "Meuleveldlaan 30", purchasePrice: 18000, normalPrice: 35000, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 45 },
  { id: "excel-row-46", itemNo: "ART.32", name: "Kettal Bitta daybed incl. cushions (price incl. BTW)", category: "Outdoor", location: "Meuleveldlaan 30", purchasePrice: 5002, normalPrice: 10005, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 46 },
  { id: "excel-row-47", itemNo: "ART.33", name: "Borley kitchen, color truffle brown, size 3400 x 800", category: "Outdoor", location: "", purchasePrice: 6200, normalPrice: 24900, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "", productUrl: "", expectedDelivery: "", notes: "", images: [], sourceRow: 47 },

  { id: "novalis-2026-09-14-01", itemNo: "ART.34", name: "Maxalto Febo Dining Chair with arms", category: "Furniture", location: "", purchasePrice: 5399.02, normalPrice: 10860, quantity: 6, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "Novalis", productUrl: "", expectedDelivery: "", notes: "Novalis offerte 14-09-2026. Aankoopprijs gebaseerd op handgeschreven € 4.462 ex. btw × 1,21. Totaalprijs voor 6 stoelen; aantal is alleen informatief.", images: ["/furniture-procurement/novalis/IMG_5780.jpg", "/furniture-procurement/novalis/IMG_5738.jpg", "/furniture-procurement/novalis/IMG_5770.jpg", "/furniture-procurement/novalis/IMG_5779.jpg"], sourceRow: 1001 },
  { id: "novalis-2026-09-14-02", itemNo: "ART.35", name: "Bieke Casteleyn Oval 350 Dining Table, 350×150", category: "Furniture", location: "", purchasePrice: 6798.99, normalPrice: 15888, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "Novalis", productUrl: "", expectedDelivery: "", notes: "Novalis offerte 14-09-2026. Aankoopprijs gebaseerd op handgeschreven € 5.619 ex. btw × 1,21.", images: ["/furniture-procurement/novalis/IMG_5739.jpg", "/furniture-procurement/novalis/IMG_5970.jpg"], sourceRow: 1002 },
  { id: "novalis-2026-09-14-03", itemNo: "ART.36", name: "Cassina 577 Dudet Sofa + Dudet Armchair", category: "Furniture", location: "", purchasePrice: 5048.12, normalPrice: 10340, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "Novalis", productUrl: "", expectedDelivery: "", notes: "Novalis offerte 14-09-2026. Setprijs: sofa + armchair. Aankoop € 4.172 ex. btw × 1,21; prijs is bewust niet over de onderdelen verdeeld.", images: ["/furniture-procurement/novalis/IMG_5948.jpg"], sourceRow: 1003 },
  { id: "novalis-2026-09-14-04", itemNo: "ART.37", name: "B&B Italia Tufty Time 20 composition", category: "Furniture", location: "", purchasePrice: 10799.25, normalPrice: 20822, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "Novalis", productUrl: "", expectedDelivery: "", notes: "Novalis offerte 14-09-2026. Aankoopprijs gebaseerd op handgeschreven € 8.925 ex. btw × 1,21.", images: ["/furniture-procurement/novalis/IMG_5771.jpg", "/furniture-procurement/novalis/IMG_5989.jpg", "/furniture-procurement/novalis/IMG_5990.jpg"], sourceRow: 1004 },
  { id: "novalis-2026-09-14-05", itemNo: "ART.38", name: "Moooi Oblique Big", category: "Accessories", location: "", purchasePrice: 1500.40, normalPrice: 3363, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "Novalis", productUrl: "", expectedDelivery: "", notes: "Novalis offerte 14-09-2026. Aankoopprijs gebaseerd op handgeschreven € 1.240 ex. btw × 1,21. Nog geen foto met voldoende zekerheid gekoppeld.", images: [], sourceRow: 1005 },
  { id: "novalis-2026-09-14-06", itemNo: "ART.39", name: "Gallotti & Radice Nori Coffee Table L + S", category: "Furniture", location: "", purchasePrice: 2698.30, normalPrice: 7297, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "Novalis", productUrl: "", expectedDelivery: "", notes: "Novalis offerte 14-09-2026. Setprijs voor Nori Coffee Table L + S. Aankoop € 2.230 ex. btw × 1,21; prijs is niet over de twee tafels verdeeld.", images: ["/furniture-procurement/novalis/IMG_5957.jpg", "/furniture-procurement/novalis/IMG_5989.jpg"], sourceRow: 1006 },
  { id: "novalis-2026-09-14-07", itemNo: "ART.40", name: "Maxalto Febo Bergere + Headrest + Pouf", category: "Furniture", location: "", purchasePrice: 2299.00, normalPrice: 5494, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "Novalis", productUrl: "", expectedDelivery: "", notes: "Novalis offerte 14-09-2026. Setprijs voor Bergere + Headrest + Pouf. Aankoop € 1.900 ex. btw × 1,21; prijs is niet over de onderdelen verdeeld.", images: ["/furniture-procurement/novalis/IMG_5991.jpg", "/furniture-procurement/novalis/IMG_5992.jpg"], sourceRow: 1007 },
  { id: "novalis-2026-09-14-08", itemNo: "ART.41", name: "Knoll Pillo Sofa + Pillo Lounge Chair Swivel", category: "Furniture", location: "", purchasePrice: 9999.44, normalPrice: 21359, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "Novalis", productUrl: "", expectedDelivery: "", notes: "Novalis offerte 14-09-2026. Setprijs voor sofa + lounge chair. Aankoop € 8.264 ex. btw × 1,21; prijs is niet over de onderdelen verdeeld.", images: ["/furniture-procurement/novalis/IMG_5971.jpg", "/furniture-procurement/novalis/IMG_5972.jpg", "/furniture-procurement/novalis/IMG_5973.jpg", "/furniture-procurement/novalis/IMG_5987.jpg"], sourceRow: 1008 },
  { id: "novalis-2026-09-14-09", itemNo: "ART.42", name: "Penta Misty Mini Composition", category: "Lighting", location: "", purchasePrice: 9598.93, normalPrice: 25955, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "Novalis", productUrl: "", expectedDelivery: "", notes: "Novalis offerte 14-09-2026. Aankoopprijs gebaseerd op handgeschreven € 7.933 ex. btw × 1,21.", images: ["/furniture-procurement/novalis/IMG_5976.jpg", "/furniture-procurement/novalis/IMG_5977.jpg"], sourceRow: 1009 },
  { id: "novalis-2026-09-14-10", itemNo: "ART.43", name: "Martinelli Luce Pipistrello", category: "Lighting", location: "", purchasePrice: 1449.58, normalPrice: 2941, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "Novalis", productUrl: "", expectedDelivery: "", notes: "Novalis offerte 14-09-2026. Aankoopprijs gebaseerd op handgeschreven € 1.198 ex. btw × 1,21. Nog geen foto met voldoende zekerheid gekoppeld.", images: [], sourceRow: 1010 },
  { id: "novalis-2026-09-14-11", itemNo: "ART.44", name: "Van Rossum GOT Stool + GOT Console", category: "Furniture", location: "", purchasePrice: 5799.53, normalPrice: 13098, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "Novalis", productUrl: "", expectedDelivery: "", notes: "Novalis offerte 14-09-2026. Setprijs voor stool + console. Aankoop € 4.793 ex. btw × 1,21; prijs is niet over de onderdelen verdeeld.", images: ["/furniture-procurement/novalis/IMG_5965.jpg"], sourceRow: 1011 },
  { id: "novalis-2026-09-14-12", itemNo: "ART.45", name: "Cassina Soriana Armchair", category: "Furniture", location: "", purchasePrice: 2199.78, normalPrice: 5065, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "Novalis", productUrl: "", expectedDelivery: "", notes: "Novalis offerte 14-09-2026. Aankoopprijs gebaseerd op handgeschreven € 1.818 ex. btw × 1,21. Foto-identificatie IMG_6005 is voorlopig.", images: ["/furniture-procurement/novalis/IMG_6005.jpg"], sourceRow: 1012 },
  { id: "novalis-2026-09-14-13", itemNo: "ART.46", name: "Fiam Shift Mirror", category: "Accessories", location: "", purchasePrice: 3899.83, normalPrice: 7826, quantity: 1, status: "Geselecteerd", paymentStatus: "Niet betaald", supplier: "Novalis", productUrl: "", expectedDelivery: "", notes: "Novalis offerte 14-09-2026. Aankoopprijs gebaseerd op handgeschreven € 3.223 ex. btw × 1,21.", images: ["/furniture-procurement/novalis/IMG_5756.jpg", "/furniture-procurement/novalis/IMG_5966.jpg"], sourceRow: 1013 },
];
