export type FurnitureItem = {
  id: string;
  itemNo: string;
  name: string;
  category: string;
  location: string;
  purchasePrice: number;
  normalPrice: number;
  quantity: number;
  status: string;
  paymentStatus: string;
  supplier: string;
  productUrl: string;
  expectedDelivery: string;
  notes: string;
  images: string[];
  sourceRow?: number;
};

export const initialFurnitureItems: FurnitureItem[] = [
  {
    "id": "excel-9",
    "itemNo": "ART.01",
    "name": "Minotti sofa color:",
    "category": "Furniture",
    "location": "Calderon",
    "purchasePrice": 14970.0,
    "normalPrice": 24000.0,
    "quantity": 1,
    "status": "Geselecteerd",
    "paymentStatus": "Volledig betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [
      "/furniture-items/row-9-1.png"
    ],
    "sourceRow": 9
  },
  {
    "id": "excel-10",
    "itemNo": "ART.02",
    "name": "Lounge chair Vitra ( with hocker)",
    "category": "Furniture",
    "location": "Calderon",
    "purchasePrice": 3800.0,
    "normalPrice": 8600.0,
    "quantity": 1,
    "status": "Geselecteerd",
    "paymentStatus": "Volledig betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [
      "/furniture-items/row-10-1.png"
    ],
    "sourceRow": 10
  },
  {
    "id": "excel-11",
    "itemNo": "ART.03",
    "name": "Dining table Allinea Angelo 1.80",
    "category": "Furniture",
    "location": "calle margarita 7",
    "purchasePrice": 10000.0,
    "normalPrice": 23000.0,
    "quantity": 1,
    "status": "Geselecteerd",
    "paymentStatus": "Volledig betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [],
    "sourceRow": 11
  },
  {
    "id": "excel-12",
    "itemNo": "ART.04",
    "name": "Salon table( alnea Angelo Kyknos 1.60x 1,15)",
    "category": "Furniture",
    "location": "calle margarita 7",
    "purchasePrice": 3500.0,
    "normalPrice": 8900.0,
    "quantity": 1,
    "status": "Geselecteerd",
    "paymentStatus": "Volledig betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [
      "/furniture-items/row-12-1.png"
    ],
    "sourceRow": 12
  },
  {
    "id": "excel-13",
    "itemNo": "ART.05",
    "name": "B&B Italia Husk with hocker ( beige linnen and black leather cusions)",
    "category": "Furniture",
    "location": "meuleveldlaan 30",
    "purchasePrice": 1500.0,
    "normalPrice": 3300.0,
    "quantity": 1,
    "status": "Geselecteerd",
    "paymentStatus": "Volledig betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [
      "/furniture-items/row-13-1.png"
    ],
    "sourceRow": 13
  },
  {
    "id": "excel-15",
    "itemNo": "ART.06",
    "name": "Jenssen bed 1",
    "category": "Sleeping",
    "location": "Calderon de la Barca",
    "purchasePrice": 2200.0,
    "normalPrice": 4500.0,
    "quantity": 1,
    "status": "Geselecteerd",
    "paymentStatus": "Volledig betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [],
    "sourceRow": 15
  },
  {
    "id": "excel-16",
    "itemNo": "ART.07",
    "name": "Jenssen bed 2",
    "category": "Sleeping",
    "location": "Calderon de la Barca",
    "purchasePrice": 1800.0,
    "normalPrice": 3500.0,
    "quantity": 1,
    "status": "Geselecteerd",
    "paymentStatus": "Aanbetaling",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [],
    "sourceRow": 16
  },
  {
    "id": "excel-17",
    "itemNo": "ART.08",
    "name": "2 night tables and carpet",
    "category": "Sleeping",
    "location": "Calderon de la Barca",
    "purchasePrice": 500.0,
    "normalPrice": 500.0,
    "quantity": 1,
    "status": "Besteld",
    "paymentStatus": "Aanbetaling",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [],
    "sourceRow": 17
  },
  {
    "id": "excel-20",
    "itemNo": "ART.09",
    "name": "Foscarini alegro large",
    "category": "Lighting",
    "location": "Calderon",
    "purchasePrice": 2500.0,
    "normalPrice": 6890.0,
    "quantity": 1,
    "status": "Besteld",
    "paymentStatus": "Aanbetaling",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [
      "/furniture-items/row-20-1.png"
    ],
    "sourceRow": 20
  },
  {
    "id": "excel-21",
    "itemNo": "ART.10",
    "name": "Henge round 3",
    "category": "Lighting",
    "location": "Calderon",
    "purchasePrice": 5000.0,
    "normalPrice": 9000.0,
    "quantity": 1,
    "status": "Besteld",
    "paymentStatus": "Aanbetaling",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [
      "/furniture-items/row-21-1.png"
    ],
    "sourceRow": 21
  },
  {
    "id": "excel-22",
    "itemNo": "ART.11",
    "name": "Henge starlight black",
    "category": "Lighting",
    "location": "Calderon",
    "purchasePrice": 5000.0,
    "normalPrice": 9000.0,
    "quantity": 1,
    "status": "Besteld",
    "paymentStatus": "Aanbetaling",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [
      "/furniture-items/row-22-1.png"
    ],
    "sourceRow": 22
  },
  {
    "id": "excel-23",
    "itemNo": "ART.12",
    "name": "Flos Arco - Black Marble - Limited Edition 40th Anniversary",
    "category": "Lighting",
    "location": "Meuleveldlaan 30",
    "purchasePrice": 2000.0,
    "normalPrice": 6000.0,
    "quantity": 1,
    "status": "Besteld",
    "paymentStatus": "Aanbetaling",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [],
    "sourceRow": 23
  },
  {
    "id": "excel-25",
    "itemNo": "ART.13",
    "name": "Polyformdrop miror ( 1.50x 2.35 ) saddle hide",
    "category": "Accessories",
    "location": "calderon",
    "purchasePrice": 2400.0,
    "normalPrice": 5600.0,
    "quantity": 1,
    "status": "Besteld",
    "paymentStatus": "Aanbetaling",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [],
    "sourceRow": 25
  },
  {
    "id": "excel-26",
    "itemNo": "ART.14",
    "name": "2 paintings Cobra Art",
    "category": "Accessories",
    "location": "calderon",
    "purchasePrice": 3000.0,
    "normalPrice": 5000.0,
    "quantity": 1,
    "status": "Besteld",
    "paymentStatus": "Aanbetaling",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [
      "/furniture-items/row-26-1.png",
      "/furniture-items/row-26-2.png"
    ],
    "sourceRow": 26
  },
  {
    "id": "excel-27",
    "itemNo": "ART.15",
    "name": "wonderfull world  2.50 x 1.20",
    "category": "Accessories",
    "location": "meuleveldlaan 30",
    "purchasePrice": 2800.0,
    "normalPrice": 5500.0,
    "quantity": 1,
    "status": "Aanbetaling",
    "paymentStatus": "Niet betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [],
    "sourceRow": 27
  },
  {
    "id": "excel-28",
    "itemNo": "ART.16",
    "name": "Samsung TQ83S93DAEXXC oled 83\"",
    "category": "Accessories",
    "location": "",
    "purchasePrice": 3299.0,
    "normalPrice": 3299.0,
    "quantity": 1,
    "status": "Aanbetaling",
    "paymentStatus": "Niet betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [
      "/furniture-items/row-28-1.png",
      "/furniture-items/row-28-2.png"
    ],
    "sourceRow": 28
  },
  {
    "id": "excel-29",
    "itemNo": "ART.17",
    "name": "soundbar",
    "category": "Accessories",
    "location": "",
    "purchasePrice": 699.0,
    "normalPrice": 699.0,
    "quantity": 1,
    "status": "Aanbetaling",
    "paymentStatus": "Niet betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [
      "/furniture-items/row-29-1.png"
    ],
    "sourceRow": 29
  },
  {
    "id": "excel-30",
    "itemNo": "ART.18",
    "name": "2 Devialet Phantom",
    "category": "Accessories",
    "location": "Calderon de la barca / Jose",
    "purchasePrice": 2000.0,
    "normalPrice": 3800.0,
    "quantity": 1,
    "status": "Aanbetaling",
    "paymentStatus": "Niet betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [
      "/furniture-items/row-30-1.png"
    ],
    "sourceRow": 30
  },
  {
    "id": "excel-31",
    "itemNo": "ART.19",
    "name": "2 mirrors metal 90 x 2.30",
    "category": "Accessories",
    "location": "meuleveldlaan 30",
    "purchasePrice": 3400.0,
    "normalPrice": 5600.0,
    "quantity": 1,
    "status": "Aanbetaling",
    "paymentStatus": "Niet betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [
      "/furniture-items/row-31-1.png"
    ],
    "sourceRow": 31
  },
  {
    "id": "excel-32",
    "itemNo": "ART.20",
    "name": "Sumo Helmut Newton XXL",
    "category": "Accessories",
    "location": "meuleveldlaan 30",
    "purchasePrice": 6000.0,
    "normalPrice": 7500.0,
    "quantity": 1,
    "status": "Aanbetaling",
    "paymentStatus": "Niet betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [
      "/furniture-items/row-32-1.png"
    ],
    "sourceRow": 32
  },
  {
    "id": "excel-33",
    "itemNo": "ART.21",
    "name": "Annie Leibovitz Limited Edition Keith Haring",
    "category": "Accessories",
    "location": "meuleveldlaan 30",
    "purchasePrice": 3000.0,
    "normalPrice": 4500.0,
    "quantity": 1,
    "status": "Aanbetaling",
    "paymentStatus": "Niet betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [],
    "sourceRow": 33
  },
  {
    "id": "excel-35",
    "itemNo": "ART.22",
    "name": "Pool table 2.63 x 1.42 M",
    "category": "Funrooms",
    "location": "Meuleveldlaan 30",
    "purchasePrice": 4000.0,
    "normalPrice": 4000.0,
    "quantity": 1,
    "status": "Onderweg",
    "paymentStatus": "Niet betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [],
    "sourceRow": 35
  },
  {
    "id": "excel-38",
    "itemNo": "ART.23",
    "name": "Kamado grill",
    "category": "Outdoor",
    "location": "Calderon de Barca",
    "purchasePrice": 2350.0,
    "normalPrice": 2393.0,
    "quantity": 1,
    "status": "Onderweg",
    "paymentStatus": "Niet betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [],
    "sourceRow": 38
  },
  {
    "id": "excel-39",
    "itemNo": "ART.24",
    "name": "6 dining with table 2.80 and carpet",
    "category": "Outdoor",
    "location": "",
    "purchasePrice": 1500.0,
    "normalPrice": 0,
    "quantity": 1,
    "status": "Onderweg",
    "paymentStatus": "Niet betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [],
    "sourceRow": 39
  },
  {
    "id": "excel-40",
    "itemNo": "ART.25",
    "name": "2 single daybeds 1 double",
    "category": "Outdoor",
    "location": "",
    "purchasePrice": 1200.0,
    "normalPrice": 0,
    "quantity": 1,
    "status": "Onderweg",
    "paymentStatus": "Niet betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [],
    "sourceRow": 40
  },
  {
    "id": "excel-41",
    "itemNo": "ART.26",
    "name": "6 kettal maya outdoor chair with black cusion",
    "category": "Outdoor",
    "location": "Meuleveldlaan 30",
    "purchasePrice": 5000.0,
    "normalPrice": 7200.0,
    "quantity": 1,
    "status": "Onderweg",
    "paymentStatus": "Niet betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [
      "/furniture-items/row-41-1.png",
      "/furniture-items/row-41-2.png"
    ],
    "sourceRow": 41
  },
  {
    "id": "excel-42",
    "itemNo": "ART.27",
    "name": "Kettal Plumon lounge ( price incl btw)",
    "category": "Outdoor",
    "location": "Meuleveldlaan 30",
    "purchasePrice": 23150.0,
    "normalPrice": 46301.0,
    "quantity": 1,
    "status": "Onderweg",
    "paymentStatus": "Niet betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [
      "/furniture-items/row-42-1.png"
    ],
    "sourceRow": 42
  },
  {
    "id": "excel-43",
    "itemNo": "ART.28",
    "name": "Kettal Plumon Dining set ( price incl btw)",
    "category": "Outdoor",
    "location": "Meuleveldlaan 30",
    "purchasePrice": 18715.0,
    "normalPrice": 37430.0,
    "quantity": 1,
    "status": "Onderweg",
    "paymentStatus": "Niet betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [
      "/furniture-items/row-43-1.png"
    ],
    "sourceRow": 43
  },
  {
    "id": "excel-44",
    "itemNo": "ART.29",
    "name": "Minotti patio lounge ( price incl BTW)",
    "category": "Outdoor",
    "location": "Meuleveldlaan 30",
    "purchasePrice": 32021.0,
    "normalPrice": 64042.0,
    "quantity": 1,
    "status": "Geleverd",
    "paymentStatus": "Niet betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [
      "/furniture-items/row-44-1.png"
    ],
    "sourceRow": 44
  },
  {
    "id": "excel-45",
    "itemNo": "ART.30",
    "name": "Minotti Torii nest dining 8 chairs table 2.80 M",
    "category": "Outdoor",
    "location": "Meuleveldlaan 30",
    "purchasePrice": 18000.0,
    "normalPrice": 35000.0,
    "quantity": 1,
    "status": "Geleverd",
    "paymentStatus": "Niet betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [],
    "sourceRow": 45
  },
  {
    "id": "excel-46",
    "itemNo": "ART.31",
    "name": "Kettal Bitta daybed incl cushions ( price incl BTW)",
    "category": "Outdoor",
    "location": "Meuleveldlaan 30",
    "purchasePrice": 5002.0,
    "normalPrice": 10005.0,
    "quantity": 1,
    "status": "Geleverd",
    "paymentStatus": "Niet betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [
      "/furniture-items/row-46-1.png"
    ],
    "sourceRow": 46
  },
  {
    "id": "excel-47",
    "itemNo": "ART.32",
    "name": "Borley kitchen, color truffle brown, size 3400x 800",
    "category": "Outdoor",
    "location": "",
    "purchasePrice": 6200.0,
    "normalPrice": 24900.0,
    "quantity": 1,
    "status": "Geleverd",
    "paymentStatus": "Niet betaald",
    "supplier": "",
    "productUrl": "",
    "expectedDelivery": "",
    "notes": "",
    "images": [
      "/furniture-items/row-47-1.png"
    ],
    "sourceRow": 47
  }
];
