import {randomUUID} from "node:crypto";
import type {Transaction} from "@libsql/client";
import type {Task,TaskStep} from "./types";
import type {User} from "../portal/permissions";
export const progressSchema=[
 `CREATE TABLE IF NOT EXISTS task_progress(task_id TEXT PRIMARY KEY REFERENCES tasks(id),created_at TEXT NOT NULL DEFAULT '',pipeline TEXT NOT NULL DEFAULT '[]',current_step TEXT NOT NULL DEFAULT '',latest_action TEXT NOT NULL DEFAULT '',latest_at TEXT NOT NULL DEFAULT '')`,
 `CREATE TABLE IF NOT EXISTS task_activity(id TEXT PRIMARY KEY,task_id TEXT NOT NULL REFERENCES tasks(id),body TEXT NOT NULL,actor TEXT NOT NULL,created_at TEXT NOT NULL)`
];
export function validatePipeline(input:unknown):TaskStep[]{if(!Array.isArray(input)||input.length>30)throw new Error('Maximaal 30 pipelinefasen.');const ids=new Set<string>();return input.map(value=>{if(!value||typeof value.id!=='string'||!value.id||value.id.length>100||ids.has(value.id))throw new Error('Controleer de pipelinefasen.');ids.add(value.id);if(typeof value.name!=='string'||!value.name.trim()||value.name.length>150||typeof value.note!=='string'||value.note.length>4000||typeof value.date!=='string'||(value.date&&(!/^\d{4}-\d{2}-\d{2}$/.test(value.date)||!Number.isFinite(Date.parse(value.date+'T12:00:00Z'))||new Date(value.date+'T12:00:00Z').toISOString().slice(0,10)!==value.date)))throw new Error('Geef elke fase een naam en een geldige datum.');return{id:value.id,name:value.name.trim(),date:value.date,note:value.note.trim()};});}
export async function activity(tx:Transaction,actor:User,id:string,body:string){const now=new Date().toISOString();await tx.execute({sql:'INSERT INTO task_activity(id,task_id,body,actor,created_at) VALUES(?,?,?,?,?)',args:[randomUUID(),id,body,actor.name,now]});await tx.execute({sql:"INSERT INTO task_progress(task_id,latest_action,latest_at) VALUES(?,?,?) ON CONFLICT(task_id) DO UPDATE SET latest_action=excluded.latest_action,latest_at=excluded.latest_at",args:[id,body,now]});await tx.execute({sql:'UPDATE tasks SET updated_at=? WHERE id=?',args:[now,id]});}
export async function saveProgress(tx:Transaction,actor:User,id:string,input:Pick<Task,"pipeline"|"currentStepId">,isNew:boolean){const old=(await tx.execute({sql:'SELECT * FROM task_progress WHERE task_id=?',args:[id]})).rows[0];const pipeline=validatePipeline(input.pipeline??(old?JSON.parse(String(old.pipeline)):[]));const current=input.currentStepId??String(old?.current_step??'');if(typeof current!=='string'||(current&&!pipeline.some(s=>s.id===current)))throw new Error('Kies een bestaande pipelinefase.');let body=isNew?'Taak gegeven':'Taakgegevens bijgewerkt';const changed=JSON.stringify(pipeline)!==String(old?.pipeline??'[]')||current!==String(old?.current_step??'');if(changed){const previous:TaskStep[]=JSON.parse(String(old?.pipeline??'[]'));const edited=[...pipeline].reverse().find(s=>JSON.stringify(s)!==JSON.stringify(previous.find(v=>v.id===s.id)));const step=current!==String(old?.current_step??'')?pipeline.find(s=>s.id===current):edited??pipeline.find(s=>s.id===current);body=step?step.name+(step.date?' · '+step.date:'')+(step.note?' — '+step.note:''):'Pipeline bijgewerkt';}await tx.execute({sql:'INSERT INTO task_progress(task_id,created_at,pipeline,current_step) VALUES(?,?,?,?) ON CONFLICT(task_id) DO UPDATE SET pipeline=excluded.pipeline,current_step=excluded.current_step',args:[id,isNew?new Date().toISOString():'',JSON.stringify(pipeline),current]});await activity(tx,actor,id,body);}
