import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {rm} from 'node:fs/promises';
import {db,schema} from '../lib/portal/db';
import {hashPassword,verifyPassword,tokenHash} from '../lib/portal/password';
import {mutateUser,newSession,sessionUser,consumeLimit,toUser,type Mutation} from '../lib/portal/store';
import {canVisit,pathPermission,type User} from '../lib/portal/permissions';
const file='/tmp/portal-'+randomUUID()+'.db';process.env.TURSO_DATABASE_URL='file:'+file;
const employee='employee';const viewer='viewer';
const base:Mutation={kind:'save',id:viewer,version:1,name:'Jan',email:'jan@example.com',role:'viewer',active:true,permissions:['los-naranjos'],password:'lang-wachtwoord-123'};
before(async()=>{await db().batch(schema,'write');for(const [id,role] of [[employee,'employee'],[viewer,'viewer']]) await db().execute({sql:'INSERT INTO portal_users(id,name,email,password_hash,role,permissions) VALUES (?,?,?,?,?,?)',args:[id,id,id+'@example.com',await hashPassword('lang-wachtwoord-123'),role,JSON.stringify(['los-naranjos'])]});});
after(async()=>{db().close();await rm(file,{force:true});});
test('passwords are salted, verified, and reject wrong or oversized input',async()=>{const first=await hashPassword('lang-wachtwoord-123');const second=await hashPassword('lang-wachtwoord-123');assert.notEqual(first,second);assert.equal(await verifyPassword('lang-wachtwoord-123',first),true);assert.equal(await verifyPassword('wrong',first),false);assert.equal(await verifyPassword('x'.repeat(129),first),false);});
test('viewer permissions are isolated, unknown paths denied',()=>{const user:User={id:viewer,name:'Jan',email:'jan@example.com',role:'viewer',active:true,permissions:['los-naranjos'],version:1};assert.equal(canVisit(user,'/reports/los-naranjos'),true);for(const path of ['/reports/la-carolina','/reports/unknown','/complete-portfolio','/beheer','/api/private','/portfolio','/portfolio-evil']) assert.equal(canVisit(user,path),false,path);assert.equal(pathPermission('/reports/los-naranjos/cashflow'),'los-naranjos');assert.equal(canVisit({...user,permissions:['spain']},'/reports/la-carolina'),false);assert.equal(canVisit({...user,active:false},'/portal'),false);
 const returns={...user,permissions:['returns']};
 assert.equal(canVisit(returns,'/api/rendements-projects'),true);
 assert.equal(canVisit(returns,'/api/rendements-projects/id','GET'),true);
 for(const method of ['POST','PUT','PATCH','DELETE']) assert.equal(canVisit(returns,'/api/rendements-projects/id',method),false);
 assert.equal(canVisit(user,'/qa'),false);
 assert.equal(canVisit(user,'/qa/index.html'),false);
 assert.equal(canVisit(user,'/photos/losnaranjos/photo1.jpg'),true);
 assert.equal(canVisit(user,'/photos/la-carolina/photo1.jpg'),false);
 assert.equal(canVisit(user,'/photos/new-project/photo1.jpg'),false);
 assert.equal(canVisit({...user,permissions:['netherlands']},'/portfolio-photos-nl-es/bevrijdingsweg-39.jpg'),true);
 assert.equal(canVisit({...user,permissions:['netherlands']},'/portfolio-photos-nl-es/los-naranjos.jpg'),false);
 assert.equal(canVisit(user,'/reports/New%20project'),false);
 const furniture={...user,permissions:['furniture']};
 assert.equal(canVisit(furniture,'/api/furniture-items'),true);
 assert.equal(canVisit(furniture,'/api/furniture-images'),true);
 assert.equal(canVisit(furniture,'/api/furniture-items/id','PATCH'),false);
 assert.equal(canVisit(furniture,'/api/product-import','POST'),false);});
test('sessions are hashed and forged/expired tokens fail',async()=>{const token=await newSession(viewer);assert.equal((await sessionUser(token))?.id,viewer);assert.equal(await sessionUser('true'),null);assert.equal(await sessionUser('0'.repeat(64)),null);const stored=await db().execute({sql:'SELECT token_hash FROM portal_sessions WHERE user_id=?',args:[viewer]});assert.equal(stored.rows[0].token_hash,tokenHash(token));await db().execute({sql:'UPDATE portal_sessions SET expires=0 WHERE token_hash=?',args:[tokenHash(token)]});assert.equal(await sessionUser(token),null);});
test('viewer cannot manage users',async()=>{await assert.rejects(mutateUser(viewer,base),/mag geen gebruikers/);});
test('self removal, self block and self demotion are forbidden',async()=>{for(const mutation of [{kind:'delete'},{active:false},{role:'viewer'}]) await assert.rejects(mutateUser(employee,{...base,id:employee,...mutation} as Mutation),/eigen toegang/);});
test('duplicate accounts and invalid permissions are rejected',async()=>{await assert.rejects(mutateUser(employee,{...base,kind:'create',id:'',email:employee+'@example.com'}),/bestaat al/);await assert.rejects(mutateUser(employee,{...base,kind:'create',id:'',permissions:['unknown']}),/Onbekend/);});
test('blocking revokes existing sessions immediately, stale changes fail',async()=>{const token=await newSession(viewer);await mutateUser(employee,{...base,email:viewer+'@example.com',active:false});assert.equal(await sessionUser(token),null);await assert.rejects(mutateUser(employee,base),/inmiddels gewijzigd/);const row=(await db().execute({sql:'SELECT * FROM portal_users WHERE id=?',args:[viewer]})).rows[0];assert.equal(toUser(row).active,false);await mutateUser(employee,{...base,email:viewer+'@example.com',version:2,active:true});});
test('concurrent updates cannot silently overwrite each other',async()=>{const results=await Promise.allSettled([mutateUser(employee,{...base,email:viewer+'@example.com',version:3,name:'First'}),mutateUser(employee,{...base,email:viewer+'@example.com',version:3,name:'Second'})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.filter(r=>r.status==='rejected').length,1);});
test('password changes revoke sessions and deletion removes accounts',async()=>{const token=await newSession(viewer);await mutateUser(employee,{...base,version:4,kind:'password',password:'nieuw-wachtwoord-123'});assert.equal(await sessionUser(token),null);const row=(await db().execute({sql:'SELECT * FROM portal_users WHERE id=?',args:[viewer]})).rows[0];assert.equal(await verifyPassword('lang-wachtwoord-123',String(row.password_hash)),false);assert.equal(await verifyPassword('nieuw-wachtwoord-123',String(row.password_hash)),true);await mutateUser(employee,{...base,version:5,kind:'delete'});assert.equal((await db().execute({sql:'SELECT * FROM portal_users WHERE id=?',args:[viewer]})).rows.length,0);});
test('persistent rate limits enforce thresholds and reset windows',async()=>{const key=randomUUID();assert.equal(await consumeLimit(key,2),true);assert.equal(await consumeLimit(key,2),true);assert.equal(await consumeLimit(key,2),false);await db().execute({sql:'UPDATE portal_limits SET expires=0 WHERE key=?',args:[key]});assert.equal(await consumeLimit(key,2),true);});

test('employee team overview is explicit and cannot turn a viewer into a supervisor',async()=>{const baseInput={...base,kind:'create' as const,id:'',email:'team-lead@example.com',name:'Don',role:'employee',teamOverview:true,permissions:[]};await mutateUser(employee,baseInput);const row=(await db().execute({sql:'SELECT * FROM portal_users WHERE email=?',args:[baseInput.email]})).rows[0];assert.deepEqual(toUser(row).permissions,['__task_team__']);await mutateUser(employee,{...baseInput,email:'ordinary-colleague@example.com',teamOverview:false});const ordinary=(await db().execute({sql:'SELECT * FROM portal_users WHERE email=?',args:['ordinary-colleague@example.com']})).rows[0];assert.deepEqual(toUser(ordinary).permissions,[]);await mutateUser(employee,{...baseInput,email:'external@example.com',role:'viewer'});const external=(await db().execute({sql:'SELECT * FROM portal_users WHERE email=?',args:['external@example.com']})).rows[0];assert.deepEqual(toUser(external).permissions,[]);});
