import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {rm} from 'node:fs/promises';
import {db,schema} from '../lib/portal/db';
import {taskData,saveTask,saveProject,taskDetails,addComment,syncProjects,setProjectVisibility} from '../lib/tasks/store';
import {putFile,getFile,deleteFile,fileMime} from '../lib/tasks/files';
import {canVisit,type User} from '../lib/portal/permissions';
import {sortedOpen,visibleProjects} from '../lib/tasks/types';
const file=process.cwd()+'/tests/tasks-'+randomUUID()+'.db';process.env.TURSO_DATABASE_URL='file:'+file;
const user:User={id:'employee',name:'Siem',email:'siem@example.com',role:'employee',active:true,permissions:[],version:1};
const input={id:'',title:'Offerte controleren',description:'Controleer de mail.',projectId:'marketing',assigneeId:user.id,status:'Te doen',deadline:'2026-10-12',version:0,checklist:[{id:'one',text:'Offerte opvragen',done:true}]};
before(async()=>{await db().batch(schema,'write');for(const [id,role] of [['employee','employee'],['viewer','viewer']])await db().execute({sql:'INSERT INTO portal_users(id,name,email,password_hash,role) VALUES(?,?,?,?,?)',args:[id,id,id+'@example.com','test',role]});});
after(async()=>{db().close();await rm(file,{force:true});});
test('employee-only task access rejects viewers and blocked employees',async()=>{for(const path of ['/taken','/api/task-files','/api/task-files/file'])assert.equal(canVisit({...user,role:'viewer',permissions:['complete']},path),false);await assert.rejects(taskData({...user,id:'viewer',role:'viewer'}));await assert.rejects(saveTask({...user,active:false},input));assert.equal(canVisit(user,'/taken'),true);});
test('tasks persist one employee, checklist and deadline; stale writes fail',async()=>{await saveTask(user,input);const data=await taskData(user);const t=data.tasks[0];assert.equal(t.assigneeId,user.id);assert.equal(t.projectId,'marketing');assert.equal(t.checklist[0].done,true);await saveTask(user,{...t,status:'Bezig'});await assert.rejects(saveTask(user,{...t,title:'Stale'}),/inmiddels gewijzigd/);assert.equal((await taskData(user)).tasks[0].status,'Bezig');});
test('invalid deadlines, missing projects and viewer assignees fail',async()=>{await assert.rejects(saveTask(user,{...input,deadline:'2026-02-30'}),/deadline/);await assert.rejects(saveTask(user,{...input,assigneeId:'viewer'}),/collega/);await assert.rejects(saveTask(user,{...input,projectId:'missing'}),/project/);});
test('manual projects save metadata and can be archived',async()=>{await saveProject(user,{id:'',name:'Nieuw pand',country:'Nederland',address:'Voorbeeldstraat 1',status:'In bezit',description:'Eigen pand',source:'manual',archived:false});const p=(await taskData(user)).projects.find(p=>p.name==='Nieuw pand')!;assert.equal(p.address,'Voorbeeldstraat 1');await saveProject(user,{...p,archived:true});await assert.rejects(saveTask(user,{...input,projectId:p.id}),/actief project/);});
test('comments preserve author and are linked to their task',async()=>{const t=(await taskData(user)).tasks[0];await addComment(user,t.id,'Zie screenshot van de mail.');const details=await taskDetails(user,t.id);assert.equal(details.comments[0].name,'employee');assert.equal(details.comments[0].text,'Zie screenshot van de mail.');await assert.rejects(addComment(user,'missing','test'));});
test('private attachments persist and delete; invalid and oversized files fail',async()=>{const t=(await taskData(user)).tasks[0];await putFile(user,t.id,new File(['%PDF-1.7\nexample'],'mail.pdf'));const details=await taskDetails(user,t.id);assert.equal(details.files.length,1);const stored=await getFile(user,details.files[0].id);assert.equal(stored!.mime,'application/pdf');assert.equal(Buffer.from(stored!.data as ArrayBuffer).toString(),'%PDF-1.7\nexample');await assert.rejects(getFile({...user,role:'viewer'},details.files[0].id));await assert.rejects(putFile(user,t.id,new File(['<html>bad</html>'],'bad.png')),/Gebruik/);await assert.rejects(putFile(user,t.id,new File([new Uint8Array(3*1024*1024+1)],'large.png')),/3 MB/);await deleteFile(user,details.files[0].id);assert.equal(await getFile(user,details.files[0].id),null);assert.equal(fileMime(new Uint8Array([137,80,78,71,13,10,26,10])),'image/png');});
test('home list sorts overdue deadlines first and excludes completed tasks',()=>{const t={...input,id:'one'};assert.deepEqual(sortedOpen([{...t,id:'none',deadline:''},{...t,id:'late',deadline:'2026-10-01'},{...t,id:'done',status:'Klaar'}]).map(t=>t.id),['late','none']);});
test('portfolio import produces stable project IDs on repeated sync',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>new Response('Project,Adres,Land,Status\nLos Naranjos,Testadres,Spanje,Lopend\n');try{await syncProjects(user);const first=(await taskData(user)).projects.filter(p=>p.source==='portfolio');assert.ok(first.length>0);await syncProjects(user);assert.deepEqual((await taskData(user)).projects.filter(p=>p.source==='portfolio').map(p=>p.id),first.map(p=>p.id));}finally{globalThis.fetch=original;}});

test('hiding projects preserves tasks, seed projects, and selections across portfolio sync',async()=>{const data=await taskData(user);const p=data.projects.find(p=>p.source==='portfolio')!;await saveTask(user,{...input,projectId:p.id});await setProjectVisibility(user,[]);const hidden=await taskData(user);assert.equal(hidden.projects.find(project=>project.id===p.id)!.visible,false);assert.equal(hidden.projects.find(project=>project.id==='marketing')!.visible,true);assert.equal(hidden.projects.find(project=>project.id==='general')!.visible,true);const t=hidden.tasks.find(t=>t.projectId===p.id)!;assert.ok(t);await saveTask(user,{...t,status:'Klaar'});await assert.rejects(saveTask(user,{...input,projectId:p.id}),/actief project/);const original=globalThis.fetch;globalThis.fetch=async()=>new Response('Project,Adres,Land,Status\nLos Naranjos,Testadres,Spanje,Lopend\n');try{await syncProjects(user);assert.equal((await taskData(user)).projects.find(project=>project.id===p.id)!.visible,false);}finally{globalThis.fetch=original;}await setProjectVisibility(user,[p.id]);assert.equal((await taskData(user)).projects.find(project=>project.id===p.id)!.visible,true);await assert.rejects(setProjectVisibility({...user,role:'viewer'},[]));await assert.rejects(setProjectVisibility(user,['missing']));});

test('archived projects are excluded from project menus even when selected',()=>{const base={id:'p',name:'Pand',country:'Nederland',address:'Adres',status:'Verkocht',description:'',source:'portfolio',archived:true,visible:true};assert.deepEqual(visibleProjects([base]),[]);assert.equal(visibleProjects([{...base,archived:false}]).length,1);});

test('BV grouping uses the same six groups as Complete portefeuille',async()=>{const {getPortfolioId,PORTFOLIO_OPTIONS}=await import('../lib/portal/portfolio-groups');assert.equal(PORTFOLIO_OPTIONS.length,6);for(const option of PORTFOLIO_OPTIONS)assert.equal(getPortfolioId(option.label),option.id);assert.equal(getPortfolioId('Onbekende BV'),null);});
