import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {rm} from 'node:fs/promises';
import {db,schema} from '../lib/portal/db';
import {taskHistory,deleteTask,taskData,saveTask,saveProject,taskDetails,addComment,syncProjects,setProjectVisibility} from '../lib/tasks/store';
import {putFile,getFile,deleteFile,fileMime} from '../lib/tasks/files';
import {canVisit,type User} from '../lib/portal/permissions';
import {sortedOpen,visibleProjects} from '../lib/tasks/types';
const file=process.cwd()+'/tests/tasks-'+randomUUID()+'.db';process.env.TURSO_DATABASE_URL='file:'+file;
const user:User={id:'employee',name:'Siem',email:'siem@example.com',role:'employee',active:true,permissions:[],version:1};
const input={id:'',title:'Offerte controleren',description:'Controleer de mail.',projectId:'marketing',assigneeId:user.id,status:'Te doen',deadline:'2026-10-12',version:0,checklist:[{id:'one',text:'Offerte opvragen',done:true}]};
before(async()=>{await db().batch(schema,'write');for(const [id,role] of [['employee','employee'],['viewer','viewer']])await db().execute({sql:'INSERT INTO portal_users(id,name,email,password_hash,role) VALUES(?,?,?,?,?)',args:[id,id,id+'@example.com','test',role]});});
after(async()=>{db().close();await rm(file,{force:true});});
test('employee-only task access rejects viewers and blocked employees',async()=>{for(const path of ['/taken','/api/task-files','/api/task-files/file'])assert.equal(canVisit({...user,role:'viewer',permissions:['complete']},path),false);await assert.rejects(taskData({...user,id:'viewer',role:'viewer'}));await assert.rejects(saveTask({...user,active:false},input));assert.equal(canVisit(user,'/taken'),true);});
test('tasks persist one employee, checklist and deadline; stale writes fail',async()=>{await saveTask(user,input);const data=await taskData(user);const t=data.tasks[0];assert.equal(t.assigneeId,user.id);assert.equal(t.projectId,'marketing');assert.equal(t.checklist[0].done,true);await saveTask(user,{...t,status:'Bezig'});await assert.rejects(saveTask(user,{...t,title:'Stale'}),/inmiddels gewijzigd/);assert.equal((await taskData(user)).tasks[0].status,'Bezig');});
test('invalid deadlines, missing projects and viewer assignees fail',async()=>{await assert.rejects(saveTask(user,{...input,deadline:'2026-02-30'}),/deadline/);await assert.rejects(saveTask(user,{...input,assigneeId:'viewer'}),/collega/);await assert.rejects(saveTask(user,{...input,projectId:'missing'}),/project/);});
test('manual projects save metadata and can be archived',async()=>{await saveProject(user,{id:'',name:'Nieuw pand',country:'Nederland',address:'Voorbeeldstraat 1',status:'In bezit',description:'Eigen pand',source:'manual',archived:false});const p=(await taskData(user)).projects.find(p=>p.name==='Nieuw pand')!;assert.equal(p.address,'Voorbeeldstraat 1');await saveProject(user,{...p,archived:true});await assert.rejects(saveTask(user,{...input,projectId:p.id}),/actief project/);});
test('comments preserve author and are linked to their task',async()=>{const t=(await taskData(user)).tasks[0];await addComment(user,t.id,'Zie screenshot van de mail.');const details=await taskDetails(user,t.id);assert.equal(details.comments[0].name,'employee');assert.equal(details.comments[0].text,'Zie screenshot van de mail.');await assert.rejects(addComment(user,'missing','test'));});
test('private attachments persist and delete; invalid and oversized files fail',async()=>{const t=(await taskData(user)).tasks[0];await putFile(user,t.id,new File(['%PDF-1.7\nexample'],'mail.pdf'));const details=await taskDetails(user,t.id);assert.equal(details.files.length,1);const stored=await getFile(user,details.files[0].id);assert.equal(stored!.mime,'application/pdf');assert.equal(Buffer.from(stored!.data as ArrayBuffer).toString(),'%PDF-1.7\nexample');await assert.rejects(getFile({...user,role:'viewer'},details.files[0].id));await assert.rejects(putFile(user,t.id,new File(['<html>bad</html>'],'bad.png')),/Gebruik/);await assert.rejects(putFile(user,t.id,new File([new Uint8Array(3*1024*1024+1)],'large.png')),/3 MB/);await deleteFile(user,details.files[0].id);assert.equal(await getFile(user,details.files[0].id),null);assert.equal(fileMime(new Uint8Array([137,80,78,71,13,10,26,10])),'image/png');});
test('home list sorts overdue deadlines first and excludes completed tasks',()=>{const t={...input,id:'one'};assert.deepEqual(sortedOpen([{...t,id:'none',deadline:''},{...t,id:'late',deadline:'2026-10-01'},{...t,id:'done',status:'Klaar'}]).map(t=>t.id),['late','none']);});
test('portfolio import produces stable project IDs on repeated sync',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>new Response('Project,Adres,Land,Status\nLos Naranjos,Testadres,Spanje,Lopend\n');try{await syncProjects(user);const first=(await taskData(user)).projects.filter(p=>p.source==='portfolio');assert.ok(first.length>0);await syncProjects(user);assert.deepEqual((await taskData(user)).projects.filter(p=>p.source==='portfolio').map(p=>p.id),first.map(p=>p.id));}finally{globalThis.fetch=original;}});

test('hiding projects preserves tasks, seed projects, and selections across portfolio sync',async()=>{const data=await taskData(user);const p=data.projects.find(p=>p.source==='portfolio')!;await saveTask(user,{...input,projectId:p.id});await setProjectVisibility(user,[]);const hidden=await taskData(user);assert.equal(hidden.projects.find(project=>project.id===p.id)!.visible,false);assert.equal(hidden.projects.find(project=>project.id==='marketing')!.visible,true);assert.equal(hidden.projects.find(project=>project.id==='general')!.visible,true);const t=hidden.tasks.find(t=>t.projectId===p.id)!;assert.ok(t);await saveTask(user,{...t,status:'Klaar'});await assert.rejects(saveTask(user,{...input,projectId:p.id}),/actief project/);const original=globalThis.fetch;globalThis.fetch=async()=>new Response('Project,Adres,Land,Status\nLos Naranjos,Testadres,Spanje,Lopend\n');try{await syncProjects(user);assert.equal((await taskData(user)).projects.find(project=>project.id===p.id)!.visible,false);}finally{globalThis.fetch=original;}await setProjectVisibility(user,[p.id]);assert.equal((await taskData(user)).projects.find(project=>project.id===p.id)!.visible,true);await assert.rejects(setProjectVisibility({...user,role:'viewer'},[]));await assert.rejects(setProjectVisibility(user,['missing']));});

test('archived projects are excluded from project menus even when selected',()=>{const base={id:'p',name:'Pand',country:'Nederland',address:'Adres',status:'Verkocht',description:'',source:'portfolio',archived:true,visible:true};assert.deepEqual(visibleProjects([base]),[]);assert.equal(visibleProjects([{...base,archived:false}]).length,1);});

test('BV grouping uses the same six groups as Complete portefeuille',async()=>{const {getPortfolioId,PORTFOLIO_OPTIONS}=await import('../lib/portal/portfolio-groups');assert.equal(PORTFOLIO_OPTIONS.length,6);for(const option of PORTFOLIO_OPTIONS)assert.equal(getPortfolioId(option.label),option.id);assert.equal(getPortfolioId('Onbekende BV'),null);});

test('custom pipelines, dates and creation timestamp persist; invalid changes roll back',async()=>{const id=await saveTask(user,{...input,pipeline:[{id:'request',name:'Aangevraagd',date:'2026-10-01',note:'Per mail'},{id:'quote',name:'Offerte ontvangen',date:'',note:''}],currentStepId:'request'});let t=(await taskData(user)).tasks.find(t=>t.id===id)!;assert.ok(t.createdAt&&Number.isFinite(Date.parse(t.createdAt)));const created=t.createdAt;assert.ok(t.latestAction!.includes('Aangevraagd'));await saveTask(user,{...t,pipeline:[{id:'quote',name:'Offerte ontvangen',date:'2026-10-07',note:'Prijs akkoord'},{id:'request',name:'Aangevraagd',date:'2026-10-01',note:'Per mail'}],currentStepId:'quote'});t=(await taskData(user)).tasks.find(t=>t.id===id)!;assert.equal(t.createdAt,created);assert.equal(t.pipeline![0].id,'quote');assert.ok(t.latestAction!.includes('Prijs akkoord'));assert.equal((await taskHistory(user,id)).length,2);await assert.rejects(saveTask(user,{...t,pipeline:[{id:'bad',name:'Test',date:'2026-02-30',note:''}],currentStepId:'bad'}),/datum/);assert.equal((await taskData(user)).tasks.find(t=>t.id===id)!.version,t.version);await assert.rejects(saveTask(user,{...t,currentStepId:'missing'}),/pipelinefase/);});
test('comments and attachments become the latest task action',async()=>{const id=await saveTask(user,input);await addComment(user,id,'Leverancier gesproken');assert.ok((await taskData(user)).tasks.find(t=>t.id===id)!.latestAction!.includes('Leverancier gesproken'));await putFile(user,id,new File(['%PDF-1.7 test'],'offerte.pdf'));assert.equal((await taskData(user)).tasks.find(t=>t.id===id)!.latestAction,'Bijlage toegevoegd: offerte.pdf');});
test('task deletion checks version and removes metadata, comments and files',async()=>{const id=await saveTask(user,input);await addComment(user,id,'History');await putFile(user,id,new File(['%PDF-1.7 test'],'test.pdf'));const t=(await taskData(user)).tasks.find(t=>t.id===id)!;await assert.rejects(deleteTask(user,id,t.version+1),/gewijzigd/);await assert.rejects(deleteTask({...user,role:'viewer'},id,t.version));await deleteTask(user,id,t.version);assert.equal((await taskData(user)).tasks.some(t=>t.id===id),false);for(const table of ['task_files','task_comments','task_activity','task_progress'])assert.equal((await db().execute({sql:'SELECT task_id FROM '+table+' WHERE task_id=?',args:[id]})).rows.length,0);});
test('homepage uses latest actions and portfolio keys match stable project identities',async()=>{const {recentOpen}=await import('../lib/tasks/types');assert.deepEqual(recentOpen([{...input,id:'old',latestAt:'2026-10-01'},{...input,id:'new',latestAt:'2026-10-07'},{...input,id:'done',latestAt:'2026-10-09',status:'Klaar'}]).map(t=>t.id),['new','old']);assert.ok((await taskData(user)).projects.find(p=>p.source==='portfolio')!.portfolioKey);});

test('portfolio matching uses source identity and refuses ambiguous or foreign matches',async()=>{const {matchTaskProject}=await import('../lib/tasks/portfolio');const a={id:'a',name:'Pand',country:'Nederland',address:'Straat 1',status:'',description:'',source:'portfolio',archived:false,entity:'BV A',portfolioKey:'key-a'};const b={...a,id:'b',entity:'BV B',portfolioKey:'key-b'};assert.equal(matchTaskProject([a,b],{project:'Renamed',address:'New address',sourceKey:'key-a'})!.id,'a');assert.equal(matchTaskProject([a,b],{project:'Pand',address:'Straat 1',country:'Nederland',entity:'BV B'})!.id,'b');assert.equal(matchTaskProject([a,b],{project:'Pand',address:'Straat 1',country:'Nederland'}),undefined);assert.equal(matchTaskProject([a],{project:'Pand',address:'Straat 1',country:'Spanje'}),undefined);});



test('each task pipeline is independent and editing it preserves task details',async()=>{const {saveTaskPipeline}=await import('../lib/tasks/store');const a=await saveTask(user,input),b=await saveTask(user,input);const original=(await taskData(user)).tasks.find(t=>t.id===a)!;await saveTaskPipeline(user,a,original.version,[{id:'request',name:'Aangevraagd',date:'2026-10-07',note:'Offerte gevraagd'}],'request','Bezig');let data=await taskData(user);const edited=data.tasks.find(t=>t.id===a)!;assert.equal(edited.version,original.version+1);assert.equal(edited.title,original.title);assert.equal(edited.description,original.description);assert.deepEqual(edited.checklist,original.checklist);assert.equal(edited.assigneeId,original.assigneeId);assert.equal(edited.latestAction,'Aangevraagd · 2026-10-07 — Offerte gevraagd');assert.deepEqual(data.tasks.find(t=>t.id===b)!.pipeline,[]);await assert.rejects(saveTaskPipeline(user,a,original.version,[],'','Bezig'),/gewijzigd/);await assert.rejects(saveTaskPipeline({...user,role:'viewer'},a,edited.version,[],'','Bezig'));await assert.rejects(saveTaskPipeline(user,a,edited.version,[{id:'bad',name:'Bad',date:'2026-02-30',note:''}],'bad','Klaar'),/datum/);data=await taskData(user);assert.equal(data.tasks.find(t=>t.id===a)!.version,edited.version);assert.equal(data.tasks.find(t=>t.id===a)!.status,'Bezig');await saveTaskPipeline(user,a,edited.version,edited.pipeline,'request','Klaar');assert.equal((await taskData(user)).tasks.find(t=>t.id===a)!.status,'Klaar');});

test('editing another pipeline step records that update without changing the current phase',async()=>{const {saveTaskPipeline}=await import('../lib/tasks/store');const pipeline=[{id:'request',name:'Aanvraag',date:'',note:''},{id:'quote',name:'Offerte',date:'',note:''}];const id=await saveTask(user,{...input,pipeline,currentStepId:'request'});const t=(await taskData(user)).tasks.find(t=>t.id===id)!;await saveTaskPipeline(user,id,t.version,[pipeline[0],{...pipeline[1],note:'Prijs ontvangen'}],'request','Te doen');const result=(await taskData(user)).tasks.find(t=>t.id===id)!;assert.equal(result.currentStepId,'request');assert.equal(result.latestAction,'Offerte — Prijs ontvangen');});
