"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import type {officeData,clientDetails} from "@/lib/office/store";
import {clientRoles,stages,type ClientRole,type OfficeClient,type OfficeDeal} from "@/lib/office/types";
import {updateClient,updateDeal,readClient,reloadOffice,noteClient,attachTask} from "@/app/klanten/actions";
import {dateLabel} from "@/lib/tasks/types";
type Data=Awaited<ReturnType<typeof officeData>>;
type Details=Awaited<ReturnType<typeof clientDetails>>;
const emptyDetails:Details={activity:[],documents:[]};
const amountLabel=(deal:OfficeDeal)=>deal.amount?new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(deal.amount))+(deal.type==='Huurder'?' / maand':''):'Bedrag nog niet ingevuld';
export default function OfficeWorkspace({initial,userId,mode,initialClientId}:{initial:Data;userId:string;mode:'clients'|'pipeline';initialClientId?:string}){
 const [data,setData]=useState(initial),[selected,setSelected]=useState(initialClientId??''),[details,setDetails]=useState<Details>(emptyDetails),[editing,setEditing]=useState<OfficeClient|null>(null),[dealDraft,setDealDraft]=useState<OfficeDeal|null>(null);
 const [search,setSearch]=useState(''),[role,setRole]=useState(''),[advisor,setAdvisor]=useState(''),[archived,setArchived]=useState(false),[pipelineType,setPipelineType]=useState<ClientRole>('Koper');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[note,setNote]=useState(''),[taskChoice,setTaskChoice]=useState('');const fileRef=useRef<HTMLInputElement>(null);
 const selectedClient=data.clients.find(c=>c.id===selected);
 useEffect(()=>{let cancelled=false;if(selected)readClient(selected).then(d=>{if(!cancelled)setDetails(d)}).catch(()=>{if(!cancelled)setError('Dossierdetails konden niet worden geladen. Probeer opnieuw.');});return()=>{cancelled=true;};},[selected]);
 function openClient(id:string){setSelected(id);setDetails(emptyDetails);setEditing(null);setDealDraft(null);setNote('');setError('');setNotice('');setTaskChoice('');}
 function newClient(){setSelected('');setDealDraft(null);setError('');setEditing({id:'',name:'',email:'',phone:'',area:'',brief:'',roles:['Koper'],advisorId:userId,archived:false,version:0});}
 async function run(work:()=>Promise<void>){setBusy(true);setError('');try{await work();}catch(e){setError(e instanceof Error?e.message:'De actie is niet gelukt. Je invoer is behouden.');}finally{setBusy(false);}}
 async function saveCustomer(){if(!editing)return;await run(async()=>{const r=await updateClient(editing);if(r.error)throw new Error(r.error);if(r.data&&r.id){setData(r.data);setEditing(null);openClient(r.id);setDetails(await readClient(r.id));setNotice('Klantdossier opgeslagen.');}});}
 async function saveTrajectory(value:OfficeDeal){await run(async()=>{const r=await updateDeal(value);if(r.error)throw new Error(r.error);if(r.data){setData(r.data);setDealDraft(null);if(selected)setDetails(await readClient(selected));setNotice('Traject opgeslagen.');}});}
 async function addNote(){await run(async()=>{const r=await noteClient(selected,note);if(r.error)throw new Error(r.error);if(r.details){setDetails(r.details);setNote('');}});}
 async function linkTask(){await run(async()=>{const r=await attachTask(selected,taskChoice);if(r.error)throw new Error(r.error);if(r.data&&r.details){setData(r.data);setDetails(r.details);setTaskChoice('');}});}
 async function upload(file?:File){if(!file)return;if(file.size>3*1024*1024){setError('Maximaal 3 MB per document.');return;}await run(async()=>{const form=new FormData();form.set('clientId',selected);form.set('file',file);const response=await fetch('/api/office-files',{method:'POST',body:form});const result=await response.json();if(!response.ok)throw new Error(result.error||'Upload mislukt.');setDetails(await readClient(selected));if(fileRef.current)fileRef.current.value='';});}
 async function removeFile(id:string){if(!window.confirm('Dit document definitief verwijderen?'))return;await run(async()=>{const response=await fetch('/api/office-files/'+id,{method:'DELETE'});if(!response.ok)throw new Error('Verwijderen mislukt.');setDetails(await readClient(selected));});}
 function newDeal(){if(!selectedClient)return;setError('');setEditing(null);setDealDraft({id:'',clientId:selectedClient.id,type:selectedClient.roles[0],title:'',stage:'Nieuw',projectId:'',amount:'',notes:'',version:0});}
 const customerList=data.clients.filter(c=>c.archived===archived&&(!role||c.roles.includes(role as ClientRole))&&(!advisor||c.advisorId===advisor)&&[c.name,c.email,c.area,c.brief].some(v=>v.toLowerCase().includes(search.toLowerCase())));
 const pipelineDeals=data.deals.filter(d=>d.type===pipelineType&&data.clients.some(c=>c.id===d.clientId&&!c.archived&&(!advisor||c.advisorId===advisor)&&(!search||[c.name,d.title].some(v=>v.toLowerCase().includes(search.toLowerCase())))));
 const clientDeals=data.deals.filter(d=>d.clientId===selected),linkedIds=new Set(data.taskLinks.filter(l=>l.clientId===selected).map(l=>l.taskId));
 const memberOptions=data.members.filter(m=>m.active||m.id===editing?.advisorId);
 return <div className="office-workspace"><p className="office-eyebrow">Relaties · Projecten · Samenwerking</p><div className="office-heading"><h1>{editing?(editing.id?'Klant bewerken':'Nieuwe klant'):selectedClient?selectedClient.name:mode==='pipeline'?'Pipeline':'Klanten'}.</h1><div className="office-actions"><button className="portal-secondary" disabled={busy} onClick={()=>{if((editing||dealDraft)&&!window.confirm('Niet opgeslagen invoer sluiten en vernieuwen?'))return;void run(async()=>{setData(await reloadOffice());setEditing(null);setDealDraft(null);if(selected)setDetails(await readClient(selected));});}}>Vernieuwen</button><button disabled={busy} onClick={newClient}>+ Nieuwe klant</button></div></div><div aria-live="polite">{error&&<p role="alert" className="portal-error">{error}</p>}{notice&&<p className="portal-success">{notice}</p>}</div>
 {editing?<form className="office-card office-form" onSubmit={e=>{e.preventDefault();void saveCustomer();}}><fieldset disabled={busy}><div className="office-fields"><label>Naam<input required maxLength={150} value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>E-mailadres<input type="email" maxLength={254} value={editing.email} onChange={e=>setEditing({...editing,email:e.target.value})}/></label><label>Telefoon<input type="tel" maxLength={60} value={editing.phone} onChange={e=>setEditing({...editing,phone:e.target.value})}/></label><label>Gebied / locatie<input maxLength={300} value={editing.area} onChange={e=>setEditing({...editing,area:e.target.value})}/></label><label>Verantwoordelijke<select value={editing.advisorId} onChange={e=>setEditing({...editing,advisorId:e.target.value})}>{memberOptions.map(m=><option key={m.id} value={m.id}>{m.name}{!m.active?' (inactief)':''}</option>)}</select></label></div><fieldset><legend>Klantrollen — meerdere keuzes mogelijk</legend>{clientRoles.map(r=><label className="portal-check" key={r}><input type="checkbox" checked={editing.roles.includes(r)} onChange={e=>setEditing({...editing,roles:e.target.checked?[...editing.roles,r]:editing.roles.filter(v=>v!==r)})}/>{r}</label>)}</fieldset><label>Wensen, eisen en afspraken<textarea maxLength={16000} rows={5} value={editing.brief} onChange={e=>setEditing({...editing,brief:e.target.value})}/></label>{editing.id&&<label className="portal-check"><input type="checkbox" checked={editing.archived} onChange={e=>setEditing({...editing,archived:e.target.checked})}/>Klant archiveren</label>}<div className="office-actions"><button type="submit">Klant opslaan</button><button type="button" className="portal-secondary" onClick={()=>setEditing(null)}>Annuleren</button></div></fieldset></form>:
 selectedClient?<><button className="office-link" disabled={busy} onClick={()=>openClient('')}>← {mode==='pipeline'?'Pipeline':'Alle klanten'}</button><div className="office-heading office-space"><div>{selectedClient.roles.map(r=><span className="portal-tag" key={r}>{r}</span>)}{selectedClient.archived&&<span className="portal-tag">Archief</span>}<p>{selectedClient.email||'Geen e-mailadres'} · {selectedClient.phone||'Geen telefoonnummer'}<br/>{selectedClient.area}</p></div><div><p>Verantwoordelijke: {data.members.find(m=>m.id===selectedClient.advisorId)?.name??'Niet meer actief'}</p><button className="portal-secondary" disabled={busy} onClick={()=>{setEditing({...selectedClient});setDealDraft(null);}}>Dossier bewerken</button></div></div><div className="office-columns"><div><section className="office-card"><h2>Wensen & afspraken</h2><p className="office-pre">{selectedClient.brief||'Nog geen wensen vastgelegd.'}</p></section><section className="office-card"><div className="office-heading"><h2>Trajecten</h2><button disabled={busy||selectedClient.archived} onClick={newDeal}>+ Traject</button></div>{clientDeals.map(d=><article className="office-list-item" key={d.id}><div><strong>{d.title}</strong><p className="office-small">{d.type} · {data.projects.find(p=>p.id===d.projectId)?.name||'Project nog te bepalen'}<br/>{amountLabel(d)}</p></div><div><span className="portal-tag">{d.stage}</span><button className="office-link" disabled={busy||selectedClient.archived} onClick={()=>setDealDraft({...d})}>Bewerken</button></div></article>)}{!clientDeals.length&&<p>Voeg het eerste koop-, huur- of investeringstraject toe.</p>}
 {dealDraft&&<form className="office-form office-space" onSubmit={e=>{e.preventDefault();void saveTrajectory(dealDraft);}}><fieldset disabled={busy}><h3>{dealDraft.id?'Traject bewerken':'Nieuw traject'}</h3><label>Soort<select disabled={!!dealDraft.id} value={dealDraft.type} onChange={e=>setDealDraft({...dealDraft,type:e.target.value as ClientRole,stage:'Nieuw'})}>{selectedClient.roles.map(r=><option key={r}>{r}</option>)}</select></label><label>Naam van het traject<input required maxLength={200} value={dealDraft.title} onChange={e=>setDealDraft({...dealDraft,title:e.target.value})} placeholder="Bijvoorbeeld: woning zoeken Marbella"/></label><label>Fase<select value={dealDraft.stage} onChange={e=>setDealDraft({...dealDraft,stage:e.target.value})}>{stages[dealDraft.type].map(s=><option key={s}>{s}</option>)}</select></label><label>Project / pand<select value={dealDraft.projectId} onChange={e=>setDealDraft({...dealDraft,projectId:e.target.value})}><option value="">Nog te bepalen</option>{data.projects.filter(p=>(!p.archived&&p.visible!==false)||p.id===dealDraft.projectId).map(p=><option key={p.id} value={p.id}>{p.name}{p.country?' · '+p.country:''}</option>)}</select></label><label>{dealDraft.type==='Huurder'?'Huurbedrag / budget per maand (€)':'Bedrag / budget (€)'}<input type="number" min="0" step="0.01" value={dealDraft.amount} onChange={e=>setDealDraft({...dealDraft,amount:e.target.value})}/></label><label>Afspraken bij dit traject<textarea maxLength={12000} value={dealDraft.notes} onChange={e=>setDealDraft({...dealDraft,notes:e.target.value})}/></label><div className="office-actions"><button type="submit">Traject opslaan</button><button type="button" className="portal-secondary" onClick={()=>setDealDraft(null)}>Annuleren</button></div></fieldset></form>}</section>
 <section className="office-card"><h2>Activiteit & notities</h2><label>Nieuwe notitie<textarea maxLength={8000} value={note} onChange={e=>setNote(e.target.value)}/></label><button disabled={busy||!note.trim()} onClick={()=>void addNote()}>Notitie toevoegen</button><div className="office-space">{details.activity.map(a=><article className="office-activity" key={a.id}><p className="office-small">{a.kind} · {a.actor} · {new Date(a.at).toLocaleString('nl-NL',{timeZone:'Europe/Amsterdam'})}</p><p className="office-pre">{a.body}</p></article>)}</div></section></div><div><section className="office-card"><div className="office-heading"><h2>Vervolgacties</h2><Link className="office-link" href={'/taken?nieuw=1&klant='+selected}>+ Taak</Link></div>{data.tasks.filter(t=>linkedIds.has(t.id)).map(t=><article className="office-list-item" key={t.id}><Link href={'/taken?taak='+t.id}>{t.title}<span className="office-small office-block">{data.members.find(m=>m.id===t.assigneeId)?.name} · {dateLabel(t.deadline)}</span></Link><span className="portal-tag">{t.status}</span></article>)}{!linkedIds.size&&<p>Nog geen taken gekoppeld.</p>}<label>Bestaande taak koppelen<select value={taskChoice} onChange={e=>setTaskChoice(e.target.value)}><option value="">Kies een taak</option>{data.tasks.filter(t=>!data.taskLinks.some(l=>l.taskId===t.id)).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><button disabled={busy||!taskChoice} onClick={()=>void linkTask()}>Taak koppelen</button></section><section className="office-card"><h2>Documenten</h2><p className="office-small">Privé voor medewerkers · PNG, JPEG, WebP of PDF · maximaal 3 MB per bestand.</p>{details.documents.map(d=><div className="office-list-item" key={d.id}><a href={'/api/office-files/'+d.id}>{d.name}<span className="office-small office-block">{Math.ceil(d.size/1024)} KB</span></a><button className="office-link" disabled={busy} onClick={()=>void removeFile(d.id)}>Verwijderen</button></div>)}<label>Document toevoegen<input ref={fileRef} disabled={busy} type="file" accept="image/png,image/jpeg,image/webp,application/pdf" onChange={e=>void upload(e.target.files?.[0])}/></label></section></div></div></>:
 <><div className="office-filters"><label>Zoeken<input placeholder="Naam, e-mail of wensen…" value={search} onChange={e=>setSearch(e.target.value)}/></label>{mode==='clients'?<label>Klantrol<select value={role} onChange={e=>setRole(e.target.value)}><option value="">Alle rollen</option>{clientRoles.map(r=><option key={r}>{r}</option>)}</select></label>:<label>Traject<select value={pipelineType} onChange={e=>setPipelineType(e.target.value as ClientRole)}>{clientRoles.map(r=><option key={r}>{r}</option>)}</select></label>}<label>Verantwoordelijke<select value={advisor} onChange={e=>setAdvisor(e.target.value)}><option value="">Alle collega&apos;s</option>{data.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>{mode==='clients'&&<label>Status<select value={archived?'archived':'active'} onChange={e=>setArchived(e.target.value==='archived')}><option value="active">Actieve klanten</option><option value="archived">Archief</option></select></label>}</div>
 {mode==='clients'?<section className="office-card office-table"><table><thead><tr><th>Klant</th><th>Rollen</th><th>Gebied</th><th>Collega</th></tr></thead><tbody>{customerList.map(c=><tr key={c.id}><td><button className="office-link" disabled={busy} onClick={()=>openClient(c.id)}>{c.name}</button><span className="office-small office-block">{c.email}</span></td><td>{c.roles.map(r=><span className="portal-tag" key={r}>{r}</span>)}</td><td>{c.area||'—'}</td><td>{data.members.find(m=>m.id===c.advisorId)?.name??'—'}</td></tr>)}</tbody></table>{!customerList.length&&<div className="office-empty"><h2>{data.clients.length?'Geen klanten voor deze selectie':'Begin met je eerste klant'}</h2><p>Bewaar contactgegevens, wensen, trajecten en vervolgacties in één dossier.</p><button onClick={newClient}>+ Nieuwe klant</button></div>}</section>:<><div className="office-board">{stages[pipelineType].map(stage=><section className="office-lane" key={stage}><div className="office-heading"><h3>{stage}</h3><span>{pipelineDeals.filter(d=>d.stage===stage).length}</span></div>{pipelineDeals.filter(d=>d.stage===stage).map(d=><article className="office-deal" key={d.id}><button className="office-link" disabled={busy} onClick={()=>openClient(d.clientId)}>{data.clients.find(c=>c.id===d.clientId)?.name}</button><p>{d.title}</p><p className="office-small">{amountLabel(d)}<br/>{data.projects.find(p=>p.id===d.projectId)?.name||'Project nog te bepalen'}</p><label>Fase<select disabled={busy} value={d.stage} onChange={e=>void saveTrajectory({...d,stage:e.target.value})}>{stages[d.type].map(s=><option key={s}>{s}</option>)}</select></label></article>)}</section>)}</div>{!pipelineDeals.length&&<p>Er zijn nog geen trajecten voor deze selectie. Open een klantdossier om een traject toe te voegen.</p>}</>}
 </>}
 </div>;
}
