import "server-only";
import {randomUUID} from "node:crypto";
import type {Row,Transaction} from "@libsql/client";
import {db} from "../portal/db";
import {employee,taskData} from "../tasks/store";
import type {User} from "../portal/permissions";
import {clientRoles,stages,type OfficeClient,type OfficeDeal,type OfficeActivity,type OfficeDocument} from "./types";
const schema=[
 `CREATE TABLE IF NOT EXISTS office_clients(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL,phone TEXT NOT NULL,area TEXT NOT NULL,brief TEXT NOT NULL,roles TEXT NOT NULL,advisor_id TEXT NOT NULL,archived INTEGER NOT NULL DEFAULT 0,version INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL)`,
 `CREATE TABLE IF NOT EXISTS office_deals(id TEXT PRIMARY KEY,client_id TEXT NOT NULL REFERENCES office_clients(id),type TEXT NOT NULL,title TEXT NOT NULL,stage TEXT NOT NULL,project_id TEXT NOT NULL DEFAULT '',amount TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',version INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL)`,
 `CREATE INDEX IF NOT EXISTS office_deals_client ON office_deals(client_id)`,
 `CREATE TABLE IF NOT EXISTS office_activity(id TEXT PRIMARY KEY,client_id TEXT NOT NULL REFERENCES office_clients(id),kind TEXT NOT NULL,body TEXT NOT NULL,actor TEXT NOT NULL,created_at TEXT NOT NULL)`,
 `CREATE TABLE IF NOT EXISTS office_task_links(task_id TEXT PRIMARY KEY REFERENCES tasks(id),client_id TEXT NOT NULL REFERENCES office_clients(id))`,
 `CREATE INDEX IF NOT EXISTS office_task_clients ON office_task_links(client_id)`,
 `CREATE TABLE IF NOT EXISTS office_documents(id TEXT PRIMARY KEY,client_id TEXT NOT NULL REFERENCES office_clients(id),name TEXT NOT NULL,mime TEXT NOT NULL,size INTEGER NOT NULL,data BLOB NOT NULL,actor TEXT NOT NULL,created_at TEXT NOT NULL)`
];
let ready:Promise<void>|undefined;
export async function officeAccess(actor:User){await employee(actor);await(ready??=db().batch(schema,"write").then(()=>{}).catch(e=>{ready=undefined;throw e;}));}
const clean=(value:unknown,max:number)=>{if(typeof value!=="string"||value.length>max)throw new Error("Controleer de ingevulde gegevens.");return value.trim();};
const client=(r:Row):OfficeClient=>({id:String(r.id),name:String(r.name),email:String(r.email),phone:String(r.phone),area:String(r.area),brief:String(r.brief),roles:JSON.parse(String(r.roles)),advisorId:String(r.advisor_id),archived:!!r.archived,version:Number(r.version)});
const deal=(r:Row):OfficeDeal=>({id:String(r.id),clientId:String(r.client_id),type:r.type as OfficeDeal["type"],title:String(r.title),stage:String(r.stage),projectId:String(r.project_id),amount:String(r.amount),notes:String(r.notes),version:Number(r.version)});
async function authorizeTx(tx:Transaction,actor:User){const row=(await tx.execute({sql:"SELECT active,role FROM portal_users WHERE id=?",args:[actor.id]})).rows[0];if(!row||!row.active||row.role!=="employee")throw new Error("Je account is gewijzigd. Log opnieuw in.");}
async function record(tx:Transaction,actor:User,clientId:string,kind:string,body:string){await tx.execute({sql:"INSERT INTO office_activity(id,client_id,kind,body,actor,created_at) VALUES(?,?,?,?,?,?)",args:[randomUUID(),clientId,kind,body,actor.name,new Date().toISOString()]});}
export async function officeData(actor:User){await officeAccess(actor);const [customers,trajectories,links,tasks]=await Promise.all([db().execute("SELECT * FROM office_clients ORDER BY name"),db().execute("SELECT * FROM office_deals ORDER BY updated_at DESC"),db().execute("SELECT task_id,client_id FROM office_task_links"),taskData(actor)]);return {...tasks,clients:customers.rows.map(client),deals:trajectories.rows.map(deal),taskLinks:links.rows.map(r=>({taskId:String(r.task_id),clientId:String(r.client_id)}))};}
export async function clientDetails(actor:User,id:string){await officeAccess(actor);const exists=(await db().execute({sql:"SELECT id FROM office_clients WHERE id=?",args:[id]})).rows[0];if(!exists)throw new Error("Klant niet gevonden.");const [events,docs]=await Promise.all([db().execute({sql:"SELECT id,kind,body,actor,created_at FROM office_activity WHERE client_id=? ORDER BY created_at DESC",args:[id]}),db().execute({sql:"SELECT id,name,size FROM office_documents WHERE client_id=? ORDER BY created_at DESC",args:[id]})]);return {activity:events.rows.map(r=>({id:String(r.id),kind:String(r.kind),body:String(r.body),actor:String(r.actor),at:String(r.created_at)})) as OfficeActivity[],documents:docs.rows.map(r=>({id:String(r.id),name:String(r.name),size:Number(r.size)})) as OfficeDocument[]};}
export async function saveClient(actor:User,input:OfficeClient){await officeAccess(actor);const name=clean(input.name,150),email=clean(input.email,254),phone=clean(input.phone,60),area=clean(input.area,300),brief=clean(input.brief,16000);if(!name)throw new Error("Vul een naam in.");if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error("Vul een geldig e-mailadres in.");if(!Array.isArray(input.roles)||!input.roles.length||input.roles.some(r=>!clientRoles.includes(r)))throw new Error("Kies minimaal één geldige klantrol.");const roles=[...new Set(input.roles)];const id=input.id||randomUUID();const tx=await db().transaction("write");try{await authorizeTx(tx,actor);const old=input.id?(await tx.execute({sql:"SELECT * FROM office_clients WHERE id=?",args:[id]})).rows[0]:null;if(input.id&&(!old||Number(old.version)!==input.version))throw new Error("Dit dossier is inmiddels gewijzigd. Vernieuw de pagina en probeer opnieuw.");const advisor=(await tx.execute({sql:"SELECT active,role FROM portal_users WHERE id=?",args:[input.advisorId]})).rows[0];if(!advisor||advisor.role!=="employee"||(!advisor.active&&old?.advisor_id!==input.advisorId))throw new Error("Kies een actieve verantwoordelijke collega.");if(old){const existing=(await tx.execute({sql:"SELECT type FROM office_deals WHERE client_id=?",args:[id]})).rows; if(existing.some(r=>!roles.includes(r.type as OfficeDeal["type"])))throw new Error("Een rol met bestaande trajecten moet behouden blijven.");await tx.execute({sql:"UPDATE office_clients SET name=?,email=?,phone=?,area=?,brief=?,roles=?,advisor_id=?,archived=?,version=version+1,updated_at=? WHERE id=?",args:[name,email,phone,area,brief,JSON.stringify(roles),input.advisorId,input.archived?1:0,new Date().toISOString(),id]});}else await tx.execute({sql:"INSERT INTO office_clients(id,name,email,phone,area,brief,roles,advisor_id,updated_at) VALUES(?,?,?,?,?,?,?,?,?)",args:[id,name,email,phone,area,brief,JSON.stringify(roles),input.advisorId,new Date().toISOString()]});await record(tx,actor,id,"Dossier",old?"Klantgegevens bijgewerkt.":"Klantdossier aangemaakt.");await tx.commit();return id;}finally{tx.close();}}
export async function saveDeal(actor:User,input:OfficeDeal){await officeAccess(actor);if(!clientRoles.includes(input.type)||!stages[input.type].includes(input.stage))throw new Error("Kies een geldig traject en een bijbehorende fase.");const title=clean(input.title,200),amount=clean(input.amount,30),notes=clean(input.notes,12000);if(!title)throw new Error("Geef het traject een naam.");if(amount&&(!/^\d+(\.\d{1,2})?$/.test(amount)||!Number.isFinite(Number(amount))||Number(amount)>1e12))throw new Error("Vul een geldig bedrag in, zonder duizendtalscheiding.");const id=input.id||randomUUID();const tx=await db().transaction("write");try{await authorizeTx(tx,actor);const old=input.id?(await tx.execute({sql:"SELECT * FROM office_deals WHERE id=?",args:[id]})).rows[0]:null;if(input.id&&(!old||Number(old.version)!==input.version))throw new Error("Dit traject is inmiddels gewijzigd. Vernieuw de lijst.");if(old&&(old.client_id!==input.clientId||old.type!==input.type))throw new Error("Klant en trajectsoort kunnen niet worden gewijzigd.");const customer=(await tx.execute({sql:"SELECT roles,archived FROM office_clients WHERE id=?",args:[input.clientId]})).rows[0];if(!customer||customer.archived||!JSON.parse(String(customer.roles)).includes(input.type))throw new Error("Kies een actieve klant met deze rol.");if(input.projectId){const project=(await tx.execute({sql:"SELECT p.id,p.archived,COALESCE(v.visible,1) AS visible FROM task_projects p LEFT JOIN task_project_visibility v ON v.project_id=p.id WHERE p.id=?",args:[input.projectId]})).rows[0];if(!project||((project.archived||!project.visible)&&old?.project_id!==input.projectId))throw new Error("Kies een zichtbaar, actief project.");}if(old)await tx.execute({sql:"UPDATE office_deals SET title=?,stage=?,project_id=?,amount=?,notes=?,version=version+1,updated_at=? WHERE id=?",args:[title,input.stage,input.projectId,amount,notes,new Date().toISOString(),id]});else await tx.execute({sql:"INSERT INTO office_deals(id,client_id,type,title,stage,project_id,amount,notes,updated_at) VALUES(?,?,?,?,?,?,?,?,?)",args:[id,input.clientId,input.type,title,input.stage,input.projectId,amount,notes,new Date().toISOString()]});await record(tx,actor,input.clientId,"Pipeline",old?`${title}: ${old.stage} → ${input.stage}. Traject bijgewerkt.`:`${input.type}: ${title} aangemaakt (${input.stage}).`);await tx.commit();return id;}finally{tx.close();}}
export async function addClientNote(actor:User,id:string,body:string){await clientDetails(actor,id);const note=clean(body,8000);if(!note)throw new Error("Vul een notitie in.");const tx=await db().transaction("write");try{await authorizeTx(tx,actor);await record(tx,actor,id,"Notitie",note);await tx.commit();}finally{tx.close();}}
export async function linkClientTask(actor:User,clientId:string,taskId:string){await clientDetails(actor,clientId);const tx=await db().transaction("write");try{await authorizeTx(tx,actor);if(!(await tx.execute({sql:"SELECT id FROM tasks WHERE id=?",args:[taskId]})).rows.length)throw new Error("Taak niet gevonden.");const existing=(await tx.execute({sql:"SELECT client_id FROM office_task_links WHERE task_id=?",args:[taskId]})).rows[0];if(existing&&existing.client_id!==clientId)throw new Error("Deze taak hoort al bij een ander klantdossier.");await tx.execute({sql:"INSERT OR IGNORE INTO office_task_links(task_id,client_id) VALUES(?,?)",args:[taskId,clientId]});if(!existing)await record(tx,actor,clientId,"Taak","Een taak gekoppeld aan dit dossier.");await tx.commit();}finally{tx.close();}}
